// Copyright 2017, TCN Inc.
// All rights reserved.

// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are
// met:

//     * Redistributions of source code must retain the above copyright
// notice, this list of conditions and the following disclaimer.
//     * Redistributions in binary form must reproduce the above
// copyright notice, this list of conditions and the following disclaimer
// in the documentation and/or other materials provided with the
// distribution.
//     * Neither the name of TCN Inc. nor the names of its
// contributors may be used to endorse or promote products derived from
// this software without specific prior written permission.

// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

package templates

const MainTemplate = `// This file is generated by protoc-gen-persist
// Source File: {{.GetOrigName}}
// DO NOT EDIT !

package {{.GetImplPackage}}

{{template "import_template" .ImportList}}

{{template "implement_structs" .Structures}}

{{template "implement_services" .ServiceList}}
`
const PersistLibTemplate = `// This file is generated by protoc-gen-persist
// Source File: {{.GetOrigName}}
// DO NOT EDIT

package persist_lib

import (
	"cloud.google.com/go/spanner"
	"golang.org/x/net/context"
)

type PersistHelper struct {
{{range $srv := .ServiceList}}{{range $method := $srv.Methods}}{{if $method.IsSpanner}}
	{{if $method.IsUnary}}
	{{$method.GetName}}Param func(context.Context, map[string]interface{},func(map[string]interface{})){{end}}
	{{if $method.IsClientStreaming}}
	{{$method.GetName}}Param func(context.Context)(func(map[string]interface{}), func()){{end}}
	{{if $method.IsServerStreaming}}
	{{$method.GetName}}Param func(context.Context, map[string]interface{},func(map[string]interface{})){{end}}
{{end}}{{end}}{{end}}
}

{{range $srv := .ServiceList}}{{range $method := $srv.Methods}}{{if $method.IsSpanner}}
{{if $method.IsUnary}}
func(p *PersistHelper) {{$method.GetName}}(ctx context.Context, params map[string]interface{}, fn func(row map[string]interface{})) {
	p.{{$method.GetName}}Param(ctx, params, fn)
}
{{end}}
{{if $method.IsServerStreaming}}
func(p *PersistHelper) {{$method.GetName}}(ctx context.Context, params map[string]interface{}, fn func(row map[string]interface{})) {
	p.{{$method.GetName}}Param(ctx, params, fn)
}
{{end}}
{{if $method.IsClientStreaming}}
// given a context, returns two functions.  (feed, stop)
// feed will be called once for every row recieved by the handler
// stop will be called when the client is done streaming it expects some sort of results to be returned
// that can be marshalled into a response
func(p *PersistHelper) {{$method.GetName}}(ctx context.Context)(func(row map[string]interface{}), func() row[string]interface{}) {
	return p.{{$method.GetName}}Param(ctx)
}
{{end}}
{{end}}{{end}}{{end}}

{{range $srv := .ServiceList}}{{range $method := $srv.Methods}}{{if $method.IsSpanner}}
{{if $method.IsSelect}}
func {{$method.GetInputTypeName}}For{{$method.Desc.GetName}}(req map[string]interface{}) *spanner.Statement {
	return &{{$method.Query.String}}
}
{{else}}
func {{$method.GetInputTypeName}}For{{$method.Desc.GetName}}(req map[string]interface{}) *spanner.Mutation{
	return {{$method.Query.String}}
}
{{end}}
{{end}}{{end}}{{end}}
`
