// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/user.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/user.proto

It has these top-level messages:
	User
	Friends
	Empty
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/tcncloud/protoc-gen-persist/persist"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id              int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name            string                      `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Friends         *Friends                    `protobuf:"bytes,3,opt,name=friends" json:"friends,omitempty"`
	CreatedOn       *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	FavoriteNumbers []int64                     `protobuf:"varint,5,rep,packed,name=favorite_numbers,json=favoriteNumbers" json:"favorite_numbers,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetFriends() *Friends {
	if m != nil {
		return m.Friends
	}
	return nil
}

func (m *User) GetCreatedOn() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedOn
	}
	return nil
}

func (m *User) GetFavoriteNumbers() []int64 {
	if m != nil {
		return m.FavoriteNumbers
	}
	return nil
}

type Friends struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *Friends) Reset()                    { *m = Friends{} }
func (m *Friends) String() string            { return proto.CompactTextString(m) }
func (*Friends) ProtoMessage()               {}
func (*Friends) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Friends) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*User)(nil), "pb.User")
	proto.RegisterType((*Friends)(nil), "pb.Friends")
	proto.RegisterType((*Empty)(nil), "pb.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for UServ service

type UServClient interface {
	CreateTable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	InsertUsers(ctx context.Context, opts ...grpc.CallOption) (UServ_InsertUsersClient, error)
	GetAllUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UServ_GetAllUsersClient, error)
	SelectUserById(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error)
	UpdateUserNames(ctx context.Context, opts ...grpc.CallOption) (UServ_UpdateUserNamesClient, error)
	UpdateNameToFoo(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error)
	UpdateAllNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UServ_UpdateAllNamesClient, error)
	GetFriends(ctx context.Context, in *Friends, opts ...grpc.CallOption) (UServ_GetFriendsClient, error)
	DropTable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type uServClient struct {
	cc *grpc.ClientConn
}

func NewUServClient(cc *grpc.ClientConn) UServClient {
	return &uServClient{cc}
}

func (c *uServClient) CreateTable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.UServ/CreateTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uServClient) InsertUsers(ctx context.Context, opts ...grpc.CallOption) (UServ_InsertUsersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UServ_serviceDesc.Streams[0], c.cc, "/pb.UServ/InsertUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &uServInsertUsersClient{stream}
	return x, nil
}

type UServ_InsertUsersClient interface {
	Send(*User) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type uServInsertUsersClient struct {
	grpc.ClientStream
}

func (x *uServInsertUsersClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uServInsertUsersClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uServClient) GetAllUsers(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UServ_GetAllUsersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UServ_serviceDesc.Streams[1], c.cc, "/pb.UServ/GetAllUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &uServGetAllUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UServ_GetAllUsersClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type uServGetAllUsersClient struct {
	grpc.ClientStream
}

func (x *uServGetAllUsersClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uServClient) SelectUserById(ctx context.Context, in *User, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := grpc.Invoke(ctx, "/pb.UServ/SelectUserById", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uServClient) UpdateUserNames(ctx context.Context, opts ...grpc.CallOption) (UServ_UpdateUserNamesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UServ_serviceDesc.Streams[2], c.cc, "/pb.UServ/UpdateUserNames", opts...)
	if err != nil {
		return nil, err
	}
	x := &uServUpdateUserNamesClient{stream}
	return x, nil
}

type UServ_UpdateUserNamesClient interface {
	Send(*User) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type uServUpdateUserNamesClient struct {
	grpc.ClientStream
}

func (x *uServUpdateUserNamesClient) Send(m *User) error {
	return x.ClientStream.SendMsg(m)
}

func (x *uServUpdateUserNamesClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uServClient) UpdateNameToFoo(ctx context.Context, in *User, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.UServ/UpdateNameToFoo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uServClient) UpdateAllNames(ctx context.Context, in *Empty, opts ...grpc.CallOption) (UServ_UpdateAllNamesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UServ_serviceDesc.Streams[3], c.cc, "/pb.UServ/UpdateAllNames", opts...)
	if err != nil {
		return nil, err
	}
	x := &uServUpdateAllNamesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UServ_UpdateAllNamesClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type uServUpdateAllNamesClient struct {
	grpc.ClientStream
}

func (x *uServUpdateAllNamesClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uServClient) GetFriends(ctx context.Context, in *Friends, opts ...grpc.CallOption) (UServ_GetFriendsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_UServ_serviceDesc.Streams[4], c.cc, "/pb.UServ/GetFriends", opts...)
	if err != nil {
		return nil, err
	}
	x := &uServGetFriendsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UServ_GetFriendsClient interface {
	Recv() (*User, error)
	grpc.ClientStream
}

type uServGetFriendsClient struct {
	grpc.ClientStream
}

func (x *uServGetFriendsClient) Recv() (*User, error) {
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *uServClient) DropTable(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.UServ/DropTable", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UServ service

type UServServer interface {
	CreateTable(context.Context, *Empty) (*Empty, error)
	InsertUsers(UServ_InsertUsersServer) error
	GetAllUsers(*Empty, UServ_GetAllUsersServer) error
	SelectUserById(context.Context, *User) (*User, error)
	UpdateUserNames(UServ_UpdateUserNamesServer) error
	UpdateNameToFoo(context.Context, *User) (*Empty, error)
	UpdateAllNames(*Empty, UServ_UpdateAllNamesServer) error
	GetFriends(*Friends, UServ_GetFriendsServer) error
	DropTable(context.Context, *Empty) (*Empty, error)
}

func RegisterUServServer(s *grpc.Server, srv UServServer) {
	s.RegisterService(&_UServ_serviceDesc, srv)
}

func _UServ_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UServServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UServ/CreateTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UServServer).CreateTable(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UServ_InsertUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UServServer).InsertUsers(&uServInsertUsersServer{stream})
}

type UServ_InsertUsersServer interface {
	SendAndClose(*Empty) error
	Recv() (*User, error)
	grpc.ServerStream
}

type uServInsertUsersServer struct {
	grpc.ServerStream
}

func (x *uServInsertUsersServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uServInsertUsersServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UServ_GetAllUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UServServer).GetAllUsers(m, &uServGetAllUsersServer{stream})
}

type UServ_GetAllUsersServer interface {
	Send(*User) error
	grpc.ServerStream
}

type uServGetAllUsersServer struct {
	grpc.ServerStream
}

func (x *uServGetAllUsersServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UServ_SelectUserById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UServServer).SelectUserById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UServ/SelectUserById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UServServer).SelectUserById(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UServ_UpdateUserNames_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UServServer).UpdateUserNames(&uServUpdateUserNamesServer{stream})
}

type UServ_UpdateUserNamesServer interface {
	SendAndClose(*Empty) error
	Recv() (*User, error)
	grpc.ServerStream
}

type uServUpdateUserNamesServer struct {
	grpc.ServerStream
}

func (x *uServUpdateUserNamesServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *uServUpdateUserNamesServer) Recv() (*User, error) {
	m := new(User)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _UServ_UpdateNameToFoo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UServServer).UpdateNameToFoo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UServ/UpdateNameToFoo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UServServer).UpdateNameToFoo(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UServ_UpdateAllNames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UServServer).UpdateAllNames(m, &uServUpdateAllNamesServer{stream})
}

type UServ_UpdateAllNamesServer interface {
	Send(*User) error
	grpc.ServerStream
}

type uServUpdateAllNamesServer struct {
	grpc.ServerStream
}

func (x *uServUpdateAllNamesServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UServ_GetFriends_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Friends)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UServServer).GetFriends(m, &uServGetFriendsServer{stream})
}

type UServ_GetFriendsServer interface {
	Send(*User) error
	grpc.ServerStream
}

type uServGetFriendsServer struct {
	grpc.ServerStream
}

func (x *uServGetFriendsServer) Send(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func _UServ_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UServServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.UServ/DropTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UServServer).DropTable(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.UServ",
	HandlerType: (*UServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTable",
			Handler:    _UServ_CreateTable_Handler,
		},
		{
			MethodName: "SelectUserById",
			Handler:    _UServ_SelectUserById_Handler,
		},
		{
			MethodName: "UpdateNameToFoo",
			Handler:    _UServ_UpdateNameToFoo_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _UServ_DropTable_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InsertUsers",
			Handler:       _UServ_InsertUsers_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetAllUsers",
			Handler:       _UServ_GetAllUsers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateUserNames",
			Handler:       _UServ_UpdateUserNames_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateAllNames",
			Handler:       _UServ_UpdateAllNames_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetFriends",
			Handler:       _UServ_GetFriends_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/user.proto",
}

func init() { proto.RegisterFile("pb/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 714 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6b, 0xdb, 0x48,
	0x14, 0xce, 0xc8, 0xf1, 0x26, 0x7e, 0x66, 0x93, 0x30, 0xec, 0x82, 0xd7, 0x97, 0x0c, 0x5e, 0x42,
	0xe4, 0x5d, 0xc7, 0x0e, 0x09, 0xa5, 0xb4, 0x25, 0x60, 0xc7, 0x91, 0x13, 0x35, 0x89, 0x13, 0x64,
	0xb9, 0x25, 0xa5, 0x60, 0x2c, 0x69, 0xec, 0x0a, 0x64, 0x8d, 0xaa, 0x19, 0x07, 0x42, 0x0f, 0x85,
	0x1e, 0x7b, 0x28, 0x35, 0xbd, 0xf5, 0x1f, 0xa9, 0x8f, 0xfd, 0x17, 0x7a, 0xea, 0x7f, 0x53, 0xca,
	0x48, 0x56, 0x6c, 0x9a, 0x34, 0xd0, 0x34, 0x27, 0xcd, 0x8f, 0xf7, 0xbe, 0xef, 0x7b, 0xdf, 0x9b,
	0x27, 0xf8, 0x33, 0xb0, 0x2a, 0x43, 0x4e, 0xc3, 0x72, 0x10, 0x32, 0xc1, 0xb0, 0x12, 0x58, 0xf9,
	0xbf, 0x03, 0x1a, 0x72, 0x97, 0x8b, 0x0a, 0x0b, 0x84, 0xcb, 0x7c, 0x1e, 0x5f, 0xe5, 0x57, 0xfb,
	0x8c, 0xf5, 0x3d, 0x5a, 0x89, 0x76, 0xd6, 0xb0, 0x57, 0x11, 0xee, 0x80, 0x72, 0xd1, 0x1d, 0x04,
	0x71, 0x40, 0xe1, 0x13, 0x82, 0xf9, 0x36, 0xa7, 0x21, 0x5e, 0x02, 0xc5, 0x75, 0x72, 0x88, 0x20,
	0x35, 0x65, 0x28, 0xae, 0x83, 0x31, 0xcc, 0xfb, 0xdd, 0x01, 0xcd, 0x29, 0x04, 0xa9, 0x19, 0x23,
	0x5a, 0xe3, 0x35, 0x58, 0xe8, 0x85, 0x2e, 0xf5, 0x1d, 0x9e, 0x4b, 0x11, 0xa4, 0x66, 0xb7, 0xb2,
	0xe5, 0xc0, 0x2a, 0x37, 0xe2, 0x23, 0x23, 0xb9, 0xc3, 0x0f, 0x00, 0xec, 0x90, 0x76, 0x05, 0x75,
	0x3a, 0xcc, 0xcf, 0xcd, 0x47, 0x91, 0xf9, 0x72, 0xac, 0xa4, 0x9c, 0x28, 0x29, 0x9b, 0x89, 0x12,
	0x23, 0x33, 0x89, 0x3e, 0xf1, 0x71, 0x11, 0x56, 0x7a, 0xdd, 0x73, 0x16, 0xba, 0x82, 0x76, 0xfc,
	0xe1, 0xc0, 0xa2, 0x21, 0xcf, 0xa5, 0x49, 0x4a, 0x4d, 0x19, 0xcb, 0xc9, 0x79, 0x33, 0x3e, 0x2e,
	0xac, 0xc2, 0xc2, 0x84, 0x19, 0xff, 0x05, 0x69, 0xa9, 0x8f, 0xe7, 0x10, 0x49, 0xa9, 0x19, 0x23,
	0xde, 0x14, 0x16, 0x20, 0xad, 0x0d, 0x02, 0x71, 0xb1, 0xf5, 0x79, 0x11, 0xd2, 0xed, 0x16, 0x0d,
	0xcf, 0xf1, 0x1a, 0x64, 0xeb, 0x11, 0x97, 0xd9, 0xb5, 0x3c, 0x8a, 0x33, 0x52, 0x7e, 0x14, 0x93,
	0x9f, 0x2e, 0x0b, 0x73, 0xf8, 0x1b, 0x82, 0xac, 0xee, 0x73, 0x1a, 0x0a, 0x69, 0x0d, 0xc7, 0x8b,
	0xf2, 0x52, 0x2e, 0x67, 0xc3, 0xbe, 0xa2, 0x37, 0xe3, 0x91, 0xf2, 0x05, 0xc1, 0x9e, 0xde, 0x6c,
	0x69, 0x86, 0x49, 0xf4, 0xa6, 0x79, 0x42, 0x64, 0x5b, 0x38, 0x51, 0x5d, 0xa7, 0x44, 0xa4, 0x8a,
	0x12, 0x99, 0x98, 0x52, 0x22, 0x53, 0x4b, 0x4a, 0xe4, 0xc7, 0x1a, 0x8b, 0x04, 0x76, 0x9e, 0xd4,
	0x8e, 0xda, 0x5a, 0x8b, 0xa8, 0x55, 0x99, 0x5b, 0x8d, 0x93, 0xab, 0x97, 0xd9, 0xd5, 0xd9, 0xf4,
	0xea, 0x95, 0x7c, 0xe3, 0x31, 0xa4, 0x75, 0xdf, 0xd6, 0x1d, 0x5c, 0xeb, 0xbb, 0xe2, 0xc5, 0xd0,
	0x2a, 0xdb, 0x6c, 0x50, 0x11, 0xb6, 0x6f, 0x7b, 0x6c, 0xe8, 0xc4, 0xed, 0xb7, 0x37, 0xfa, 0xd4,
	0xdf, 0x48, 0xde, 0x89, 0xa0, 0x5c, 0x74, 0x38, 0x0d, 0xcf, 0x5d, 0x9b, 0x46, 0x8f, 0xa9, 0xc3,
	0x83, 0xae, 0xef, 0xd3, 0xb0, 0xa2, 0x22, 0xec, 0x43, 0x76, 0x9f, 0x8a, 0x9a, 0xe7, 0xc5, 0xf5,
	0xcf, 0xf8, 0x74, 0x69, 0x45, 0xe1, 0x40, 0x96, 0x5f, 0x87, 0x5a, 0x4b, 0x3b, 0xd2, 0xea, 0x26,
	0xf9, 0xc5, 0x8a, 0x49, 0xc3, 0x38, 0x39, 0x8e, 0xdd, 0xda, 0x44, 0xf8, 0x35, 0x2c, 0xb5, 0xa8,
	0x47, 0xed, 0xc8, 0xef, 0xdd, 0x0b, 0xdd, 0x99, 0xb1, 0x7c, 0xca, 0x78, 0x26, 0x19, 0x4d, 0xb8,
	0x7f, 0x4b, 0x46, 0xf8, 0x67, 0xca, 0x49, 0x9e, 0x1e, 0x68, 0x86, 0x46, 0x5c, 0x87, 0xec, 0x90,
	0xaa, 0xeb, 0xe0, 0xe7, 0xb0, 0xdc, 0x0e, 0x9c, 0xae, 0xa0, 0x92, 0xa8, 0x29, 0x9f, 0xcf, 0xf5,
	0x4d, 0xdf, 0x92, 0x12, 0x36, 0xe0, 0xff, 0x38, 0x78, 0x82, 0xc5, 0xa9, 0x88, 0x84, 0x48, 0xac,
	0xe8, 0x7b, 0x7a, 0xa8, 0x26, 0xc8, 0x45, 0xa2, 0x22, 0x6c, 0x25, 0xe8, 0x12, 0xd9, 0x64, 0x0d,
	0xc6, 0xae, 0x47, 0x7f, 0x28, 0xd1, 0xef, 0xc1, 0xf6, 0xcf, 0xd0, 0xd7, 0x7b, 0x8c, 0xad, 0x93,
	0x53, 0x43, 0x3f, 0xae, 0x19, 0x67, 0x9d, 0x43, 0xed, 0x6c, 0x4a, 0x83, 0x8b, 0xb0, 0x14, 0xa7,
	0xd5, 0x3c, 0x2f, 0x2e, 0xe0, 0xda, 0xae, 0xcd, 0x6d, 0x22, 0xfc, 0x0e, 0x01, 0xec, 0x53, 0x91,
	0x4c, 0xcf, 0xec, 0x10, 0xcf, 0x44, 0xf6, 0xa5, 0x18, 0xeb, 0xf6, 0x6e, 0xaf, 0x5f, 0x71, 0x3b,
	0xaa, 0x42, 0x6f, 0x92, 0x76, 0xb3, 0xa9, 0xb5, 0x4c, 0x35, 0xf2, 0x8a, 0x17, 0x37, 0x11, 0xfe,
	0x17, 0x32, 0x7b, 0x21, 0x0b, 0x6e, 0x1c, 0xca, 0xfc, 0xab, 0xb7, 0xe3, 0x91, 0xf2, 0x12, 0x18,
	0xdc, 0xf0, 0x2b, 0x59, 0xc9, 0x16, 0x40, 0x6e, 0x5a, 0x22, 0x74, 0xfd, 0xfe, 0x7f, 0xf5, 0xdf,
	0x9e, 0x85, 0xc0, 0x7a, 0x3f, 0x1e, 0x29, 0x68, 0xf7, 0x03, 0xfa, 0x38, 0x1e, 0x29, 0x8d, 0x3b,
	0xc0, 0x7b, 0x14, 0x58, 0xcf, 0xee, 0x08, 0xc7, 0xfa, 0x23, 0xca, 0xd9, 0xfe, 0x1e, 0x00, 0x00,
	0xff, 0xff, 0x6f, 0xc5, 0x1d, 0x07, 0x10, 0x06, 0x00, 0x00,
}
