stages:
    - build
    - deploy

build-linux:
    stage: build
    image: ubuntu:20.04 
    script:
        - apt update && apt install -y build-essential xz-utils git wget curl 
        - ./pleasew test -p -v 2 ...
        - ./pleasew build -p -v 2 ...
    artifacts:
        paths:
            - plz-out/bin/protoc-gen-persist
            - plz-out/gen/protoc-gen-persist*.tar
        expire_in: 30mins

build-osx:
    stage: build
    tags:
        - osx
    script:
        - ./pleasew test -p -v 2 ...
        - ./pleasew build -p -v 2 ...
    artifacts:
        paths:
            - plz-out/bin/protoc-gen-persist
            - plz-out/gen/protoc-gen-persist*.tar
        expire_in: 30mins

deploy:
    stage: deploy
    image: ubuntu:20.04
    dependencies:
        - build-linux
        - build-osx
    only:
        - tags
    script:
        - apt update && apt install -y curl bzip2
        - curl -Lo - https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz | tar zxf -
        - mv ghr_v0.13.0_linux_amd64/ghr .
        - mkdir artifacts
        - cp plz-out/bin/protoc-gen-persist artifacts
        - cd artifacts
        - tar cjvf protoc-gen-persist-${CI_COMMIT_TAG}-linux-amd64.tar.gz wollemi
        - cp ../plz-out/bin/darwin_amd64/protoc-gen-persist .
        - tar cjvf protoc-gen-persist-${CI_COMMIT_TAG}-darwin-amd64.tar.gz wollemi
        - rm protoc-gen-persist
        - cd ..
        - ./ghr -t ${GITHUB_TOKEN} -u tcncloud -r protoc-gen-persist -c ${CI_COMMIT_SHA} -replace  ${CI_COMMIT_TAG} ./artifacts/ 

