// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tests/spanner/basic/basic_example.proto

package basic // import "github.com/tcncloud/protoc-gen-persist/tests/spanner/basic"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/tcncloud/protoc-gen-persist/persist"
import test "github.com/tcncloud/protoc-gen-persist/tests/test"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyEnum int32

const (
	MyEnum_OPTION_0 MyEnum = 0
	MyEnum_OPTION_1 MyEnum = 1
)

var MyEnum_name = map[int32]string{
	0: "OPTION_0",
	1: "OPTION_1",
}
var MyEnum_value = map[string]int32{
	"OPTION_0": 0,
	"OPTION_1": 1,
}

func (x MyEnum) String() string {
	return proto.EnumName(MyEnum_name, int32(x))
}
func (MyEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_basic_example_562393de6fc0a21f, []int{0}
}

type MappedEnum int32

const (
	MappedEnum_OPT_0 MappedEnum = 0
	MappedEnum_OPT_1 MappedEnum = 1
)

var MappedEnum_name = map[int32]string{
	0: "OPT_0",
	1: "OPT_1",
}
var MappedEnum_value = map[string]int32{
	"OPT_0": 0,
	"OPT_1": 1,
}

func (x MappedEnum) String() string {
	return proto.EnumName(MappedEnum_name, int32(x))
}
func (MappedEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_basic_example_562393de6fc0a21f, []int{1}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_basic_example_562393de6fc0a21f, []int{0}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Something struct {
	Thing                *Something_SomethingElse `protobuf:"bytes,2,opt,name=thing,proto3" json:"thing,omitempty"`
	Myenum               MyEnum                   `protobuf:"varint,3,opt,name=myenum,proto3,enum=tests.MyEnum" json:"myenum,omitempty"`
	Mappedenum           MappedEnum               `protobuf:"varint,4,opt,name=mappedenum,proto3,enum=tests.MappedEnum" json:"mappedenum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Something) Reset()         { *m = Something{} }
func (m *Something) String() string { return proto.CompactTextString(m) }
func (*Something) ProtoMessage()    {}
func (*Something) Descriptor() ([]byte, []int) {
	return fileDescriptor_basic_example_562393de6fc0a21f, []int{1}
}
func (m *Something) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Something.Unmarshal(m, b)
}
func (m *Something) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Something.Marshal(b, m, deterministic)
}
func (dst *Something) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Something.Merge(dst, src)
}
func (m *Something) XXX_Size() int {
	return xxx_messageInfo_Something.Size(m)
}
func (m *Something) XXX_DiscardUnknown() {
	xxx_messageInfo_Something.DiscardUnknown(m)
}

var xxx_messageInfo_Something proto.InternalMessageInfo

func (m *Something) GetThing() *Something_SomethingElse {
	if m != nil {
		return m.Thing
	}
	return nil
}

func (m *Something) GetMyenum() MyEnum {
	if m != nil {
		return m.Myenum
	}
	return MyEnum_OPTION_0
}

func (m *Something) GetMappedenum() MappedEnum {
	if m != nil {
		return m.Mappedenum
	}
	return MappedEnum_OPT_0
}

type Something_SomethingElse struct {
	Thing                string   `protobuf:"bytes,1,opt,name=thing,proto3" json:"thing,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Something_SomethingElse) Reset()         { *m = Something_SomethingElse{} }
func (m *Something_SomethingElse) String() string { return proto.CompactTextString(m) }
func (*Something_SomethingElse) ProtoMessage()    {}
func (*Something_SomethingElse) Descriptor() ([]byte, []int) {
	return fileDescriptor_basic_example_562393de6fc0a21f, []int{1, 0}
}
func (m *Something_SomethingElse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Something_SomethingElse.Unmarshal(m, b)
}
func (m *Something_SomethingElse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Something_SomethingElse.Marshal(b, m, deterministic)
}
func (dst *Something_SomethingElse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Something_SomethingElse.Merge(dst, src)
}
func (m *Something_SomethingElse) XXX_Size() int {
	return xxx_messageInfo_Something_SomethingElse.Size(m)
}
func (m *Something_SomethingElse) XXX_DiscardUnknown() {
	xxx_messageInfo_Something_SomethingElse.DiscardUnknown(m)
}

var xxx_messageInfo_Something_SomethingElse proto.InternalMessageInfo

func (m *Something_SomethingElse) GetThing() string {
	if m != nil {
		return m.Thing
	}
	return ""
}

type HasTimestamp struct {
	Time                 *timestamp.Timestamp   `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Some                 *Something             `protobuf:"bytes,2,opt,name=some,proto3" json:"some,omitempty"`
	Str                  string                 `protobuf:"bytes,3,opt,name=str,proto3" json:"str,omitempty"`
	Table                *test.ExampleTable     `protobuf:"bytes,4,opt,name=table,proto3" json:"table,omitempty"`
	Strs                 []string               `protobuf:"bytes,5,rep,name=strs,proto3" json:"strs,omitempty"`
	Tables               []*test.ExampleTable   `protobuf:"bytes,6,rep,name=tables,proto3" json:"tables,omitempty"`
	Somes                []*Something           `protobuf:"bytes,7,rep,name=somes,proto3" json:"somes,omitempty"`
	Times                []*timestamp.Timestamp `protobuf:"bytes,8,rep,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HasTimestamp) Reset()         { *m = HasTimestamp{} }
func (m *HasTimestamp) String() string { return proto.CompactTextString(m) }
func (*HasTimestamp) ProtoMessage()    {}
func (*HasTimestamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_basic_example_562393de6fc0a21f, []int{2}
}
func (m *HasTimestamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HasTimestamp.Unmarshal(m, b)
}
func (m *HasTimestamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HasTimestamp.Marshal(b, m, deterministic)
}
func (dst *HasTimestamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HasTimestamp.Merge(dst, src)
}
func (m *HasTimestamp) XXX_Size() int {
	return xxx_messageInfo_HasTimestamp.Size(m)
}
func (m *HasTimestamp) XXX_DiscardUnknown() {
	xxx_messageInfo_HasTimestamp.DiscardUnknown(m)
}

var xxx_messageInfo_HasTimestamp proto.InternalMessageInfo

func (m *HasTimestamp) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *HasTimestamp) GetSome() *Something {
	if m != nil {
		return m.Some
	}
	return nil
}

func (m *HasTimestamp) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *HasTimestamp) GetTable() *test.ExampleTable {
	if m != nil {
		return m.Table
	}
	return nil
}

func (m *HasTimestamp) GetStrs() []string {
	if m != nil {
		return m.Strs
	}
	return nil
}

func (m *HasTimestamp) GetTables() []*test.ExampleTable {
	if m != nil {
		return m.Tables
	}
	return nil
}

func (m *HasTimestamp) GetSomes() []*Something {
	if m != nil {
		return m.Somes
	}
	return nil
}

func (m *HasTimestamp) GetTimes() []*timestamp.Timestamp {
	if m != nil {
		return m.Times
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "tests.Empty")
	proto.RegisterType((*Something)(nil), "tests.Something")
	proto.RegisterType((*Something_SomethingElse)(nil), "tests.Something.SomethingElse")
	proto.RegisterType((*HasTimestamp)(nil), "tests.HasTimestamp")
	proto.RegisterEnum("tests.MyEnum", MyEnum_name, MyEnum_value)
	proto.RegisterEnum("tests.MappedEnum", MappedEnum_name, MappedEnum_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExtraSrvClient is the client API for ExtraSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExtraSrvClient interface {
	ExtraUnary(ctx context.Context, in *test.NumRows, opts ...grpc.CallOption) (*test.ExampleTable, error)
	ExtraMethod(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error)
}

type extraSrvClient struct {
	cc *grpc.ClientConn
}

func NewExtraSrvClient(cc *grpc.ClientConn) ExtraSrvClient {
	return &extraSrvClient{cc}
}

func (c *extraSrvClient) ExtraUnary(ctx context.Context, in *test.NumRows, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.ExtraSrv/ExtraUnary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extraSrvClient) ExtraMethod(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.ExtraSrv/ExtraMethod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtraSrvServer is the server API for ExtraSrv service.
type ExtraSrvServer interface {
	ExtraUnary(context.Context, *test.NumRows) (*test.ExampleTable, error)
	ExtraMethod(context.Context, *test.ExampleTable) (*test.ExampleTable, error)
}

func RegisterExtraSrvServer(s *grpc.Server, srv ExtraSrvServer) {
	s.RegisterService(&_ExtraSrv_serviceDesc, srv)
}

func _ExtraSrv_ExtraUnary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.NumRows)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtraSrvServer).ExtraUnary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.ExtraSrv/ExtraUnary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtraSrvServer).ExtraUnary(ctx, req.(*test.NumRows))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExtraSrv_ExtraMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtraSrvServer).ExtraMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.ExtraSrv/ExtraMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtraSrvServer).ExtraMethod(ctx, req.(*test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExtraSrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tests.ExtraSrv",
	HandlerType: (*ExtraSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtraUnary",
			Handler:    _ExtraSrv_ExtraUnary_Handler,
		},
		{
			MethodName: "ExtraMethod",
			Handler:    _ExtraSrv_ExtraMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tests/spanner/basic/basic_example.proto",
}

// MySpannerClient is the client API for MySpanner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MySpannerClient interface {
	UniaryInsert(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error)
	UniarySelect(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error)
	UniarySelectWithDirectives(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error)
	UniaryUpdate(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.PartialTable, error)
	UniaryDeleteRange(ctx context.Context, in *test.ExampleTableRange, opts ...grpc.CallOption) (*test.ExampleTable, error)
	ServerStream(ctx context.Context, in *test.Name, opts ...grpc.CallOption) (MySpanner_ServerStreamClient, error)
	ClientStreamInsert(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamInsertClient, error)
	ClientStreamDelete(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamDeleteClient, error)
	UniarySelectWithHooks(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error)
	ServerStreamWithHooks(ctx context.Context, in *test.Name, opts ...grpc.CallOption) (MySpanner_ServerStreamWithHooksClient, error)
	ClientStreamUpdateWithHooks(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamUpdateWithHooksClient, error)
}

type mySpannerClient struct {
	cc *grpc.ClientConn
}

func NewMySpannerClient(cc *grpc.ClientConn) MySpannerClient {
	return &mySpannerClient{cc}
}

func (c *mySpannerClient) UniaryInsert(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.MySpanner/UniaryInsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniarySelect(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.MySpanner/UniarySelect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniarySelectWithDirectives(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.MySpanner/UniarySelectWithDirectives", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniaryUpdate(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.PartialTable, error) {
	out := new(test.PartialTable)
	err := c.cc.Invoke(ctx, "/tests.MySpanner/UniaryUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniaryDeleteRange(ctx context.Context, in *test.ExampleTableRange, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.MySpanner/UniaryDeleteRange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) ServerStream(ctx context.Context, in *test.Name, opts ...grpc.CallOption) (MySpanner_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MySpanner_serviceDesc.Streams[0], "/tests.MySpanner/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MySpanner_ServerStreamClient interface {
	Recv() (*test.ExampleTable, error)
	grpc.ClientStream
}

type mySpannerServerStreamClient struct {
	grpc.ClientStream
}

func (x *mySpannerServerStreamClient) Recv() (*test.ExampleTable, error) {
	m := new(test.ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) ClientStreamInsert(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamInsertClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MySpanner_serviceDesc.Streams[1], "/tests.MySpanner/ClientStreamInsert", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerClientStreamInsertClient{stream}
	return x, nil
}

type MySpanner_ClientStreamInsertClient interface {
	Send(*test.ExampleTable) error
	CloseAndRecv() (*test.NumRows, error)
	grpc.ClientStream
}

type mySpannerClientStreamInsertClient struct {
	grpc.ClientStream
}

func (x *mySpannerClientStreamInsertClient) Send(m *test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mySpannerClientStreamInsertClient) CloseAndRecv() (*test.NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(test.NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) ClientStreamDelete(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamDeleteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MySpanner_serviceDesc.Streams[2], "/tests.MySpanner/ClientStreamDelete", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerClientStreamDeleteClient{stream}
	return x, nil
}

type MySpanner_ClientStreamDeleteClient interface {
	Send(*test.ExampleTable) error
	CloseAndRecv() (*test.NumRows, error)
	grpc.ClientStream
}

type mySpannerClientStreamDeleteClient struct {
	grpc.ClientStream
}

func (x *mySpannerClientStreamDeleteClient) Send(m *test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mySpannerClientStreamDeleteClient) CloseAndRecv() (*test.NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(test.NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) UniarySelectWithHooks(ctx context.Context, in *test.ExampleTable, opts ...grpc.CallOption) (*test.ExampleTable, error) {
	out := new(test.ExampleTable)
	err := c.cc.Invoke(ctx, "/tests.MySpanner/UniarySelectWithHooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) ServerStreamWithHooks(ctx context.Context, in *test.Name, opts ...grpc.CallOption) (MySpanner_ServerStreamWithHooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MySpanner_serviceDesc.Streams[3], "/tests.MySpanner/ServerStreamWithHooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerServerStreamWithHooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MySpanner_ServerStreamWithHooksClient interface {
	Recv() (*test.ExampleTable, error)
	grpc.ClientStream
}

type mySpannerServerStreamWithHooksClient struct {
	grpc.ClientStream
}

func (x *mySpannerServerStreamWithHooksClient) Recv() (*test.ExampleTable, error) {
	m := new(test.ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) ClientStreamUpdateWithHooks(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamUpdateWithHooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MySpanner_serviceDesc.Streams[4], "/tests.MySpanner/ClientStreamUpdateWithHooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerClientStreamUpdateWithHooksClient{stream}
	return x, nil
}

type MySpanner_ClientStreamUpdateWithHooksClient interface {
	Send(*test.ExampleTable) error
	CloseAndRecv() (*test.NumRows, error)
	grpc.ClientStream
}

type mySpannerClientStreamUpdateWithHooksClient struct {
	grpc.ClientStream
}

func (x *mySpannerClientStreamUpdateWithHooksClient) Send(m *test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mySpannerClientStreamUpdateWithHooksClient) CloseAndRecv() (*test.NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(test.NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MySpannerServer is the server API for MySpanner service.
type MySpannerServer interface {
	UniaryInsert(context.Context, *test.ExampleTable) (*test.ExampleTable, error)
	UniarySelect(context.Context, *test.ExampleTable) (*test.ExampleTable, error)
	UniarySelectWithDirectives(context.Context, *test.ExampleTable) (*test.ExampleTable, error)
	UniaryUpdate(context.Context, *test.ExampleTable) (*test.PartialTable, error)
	UniaryDeleteRange(context.Context, *test.ExampleTableRange) (*test.ExampleTable, error)
	ServerStream(*test.Name, MySpanner_ServerStreamServer) error
	ClientStreamInsert(MySpanner_ClientStreamInsertServer) error
	ClientStreamDelete(MySpanner_ClientStreamDeleteServer) error
	UniarySelectWithHooks(context.Context, *test.ExampleTable) (*test.ExampleTable, error)
	ServerStreamWithHooks(*test.Name, MySpanner_ServerStreamWithHooksServer) error
	ClientStreamUpdateWithHooks(MySpanner_ClientStreamUpdateWithHooksServer) error
}

func RegisterMySpannerServer(s *grpc.Server, srv MySpannerServer) {
	s.RegisterService(&_MySpanner_serviceDesc, srv)
}

func _MySpanner_UniaryInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniaryInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.MySpanner/UniaryInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniaryInsert(ctx, req.(*test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniarySelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniarySelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.MySpanner/UniarySelect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniarySelect(ctx, req.(*test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniarySelectWithDirectives_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniarySelectWithDirectives(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.MySpanner/UniarySelectWithDirectives",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniarySelectWithDirectives(ctx, req.(*test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniaryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniaryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.MySpanner/UniaryUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniaryUpdate(ctx, req.(*test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniaryDeleteRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTableRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniaryDeleteRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.MySpanner/UniaryDeleteRange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniaryDeleteRange(ctx, req.(*test.ExampleTableRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(test.Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MySpannerServer).ServerStream(m, &mySpannerServerStreamServer{stream})
}

type MySpanner_ServerStreamServer interface {
	Send(*test.ExampleTable) error
	grpc.ServerStream
}

type mySpannerServerStreamServer struct {
	grpc.ServerStream
}

func (x *mySpannerServerStreamServer) Send(m *test.ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func _MySpanner_ClientStreamInsert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MySpannerServer).ClientStreamInsert(&mySpannerClientStreamInsertServer{stream})
}

type MySpanner_ClientStreamInsertServer interface {
	SendAndClose(*test.NumRows) error
	Recv() (*test.ExampleTable, error)
	grpc.ServerStream
}

type mySpannerClientStreamInsertServer struct {
	grpc.ServerStream
}

func (x *mySpannerClientStreamInsertServer) SendAndClose(m *test.NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mySpannerClientStreamInsertServer) Recv() (*test.ExampleTable, error) {
	m := new(test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MySpanner_ClientStreamDelete_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MySpannerServer).ClientStreamDelete(&mySpannerClientStreamDeleteServer{stream})
}

type MySpanner_ClientStreamDeleteServer interface {
	SendAndClose(*test.NumRows) error
	Recv() (*test.ExampleTable, error)
	grpc.ServerStream
}

type mySpannerClientStreamDeleteServer struct {
	grpc.ServerStream
}

func (x *mySpannerClientStreamDeleteServer) SendAndClose(m *test.NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mySpannerClientStreamDeleteServer) Recv() (*test.ExampleTable, error) {
	m := new(test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MySpanner_UniarySelectWithHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniarySelectWithHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tests.MySpanner/UniarySelectWithHooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniarySelectWithHooks(ctx, req.(*test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_ServerStreamWithHooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(test.Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MySpannerServer).ServerStreamWithHooks(m, &mySpannerServerStreamWithHooksServer{stream})
}

type MySpanner_ServerStreamWithHooksServer interface {
	Send(*test.ExampleTable) error
	grpc.ServerStream
}

type mySpannerServerStreamWithHooksServer struct {
	grpc.ServerStream
}

func (x *mySpannerServerStreamWithHooksServer) Send(m *test.ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func _MySpanner_ClientStreamUpdateWithHooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MySpannerServer).ClientStreamUpdateWithHooks(&mySpannerClientStreamUpdateWithHooksServer{stream})
}

type MySpanner_ClientStreamUpdateWithHooksServer interface {
	SendAndClose(*test.NumRows) error
	Recv() (*test.ExampleTable, error)
	grpc.ServerStream
}

type mySpannerClientStreamUpdateWithHooksServer struct {
	grpc.ServerStream
}

func (x *mySpannerClientStreamUpdateWithHooksServer) SendAndClose(m *test.NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mySpannerClientStreamUpdateWithHooksServer) Recv() (*test.ExampleTable, error) {
	m := new(test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MySpanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tests.MySpanner",
	HandlerType: (*MySpannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UniaryInsert",
			Handler:    _MySpanner_UniaryInsert_Handler,
		},
		{
			MethodName: "UniarySelect",
			Handler:    _MySpanner_UniarySelect_Handler,
		},
		{
			MethodName: "UniarySelectWithDirectives",
			Handler:    _MySpanner_UniarySelectWithDirectives_Handler,
		},
		{
			MethodName: "UniaryUpdate",
			Handler:    _MySpanner_UniaryUpdate_Handler,
		},
		{
			MethodName: "UniaryDeleteRange",
			Handler:    _MySpanner_UniaryDeleteRange_Handler,
		},
		{
			MethodName: "UniarySelectWithHooks",
			Handler:    _MySpanner_UniarySelectWithHooks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _MySpanner_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamInsert",
			Handler:       _MySpanner_ClientStreamInsert_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStreamDelete",
			Handler:       _MySpanner_ClientStreamDelete_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerStreamWithHooks",
			Handler:       _MySpanner_ServerStreamWithHooks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamUpdateWithHooks",
			Handler:       _MySpanner_ClientStreamUpdateWithHooks_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "tests/spanner/basic/basic_example.proto",
}

func init() {
	proto.RegisterFile("tests/spanner/basic/basic_example.proto", fileDescriptor_basic_example_562393de6fc0a21f)
}

var fileDescriptor_basic_example_562393de6fc0a21f = []byte{
	// 1208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x4f, 0x6f, 0x1a, 0xc7,
	0x1b, 0xfe, 0xad, 0x6d, 0x1c, 0x78, 0x8d, 0xf3, 0x23, 0x93, 0xba, 0x21, 0x1b, 0xa5, 0x5d, 0xad,
	0x92, 0x66, 0x41, 0x09, 0x10, 0x52, 0x29, 0x87, 0xca, 0x12, 0x8e, 0xd9, 0x34, 0x28, 0x31, 0x38,
	0x0b, 0x4e, 0xd2, 0xa6, 0x12, 0x1a, 0xd8, 0x09, 0xac, 0xb2, 0xff, 0xba, 0x33, 0xa4, 0x41, 0x55,
	0xa5, 0xaa, 0x87, 0x56, 0xaa, 0x54, 0xa9, 0xfe, 0x0a, 0xfd, 0x04, 0x3d, 0xfa, 0xdc, 0x43, 0xbf,
	0x4c, 0x6f, 0xbd, 0xf4, 0x5a, 0xcd, 0xcc, 0x02, 0x0b, 0x35, 0x2e, 0x71, 0x2f, 0xa3, 0x81, 0xf7,
	0x99, 0xe7, 0x7d, 0xde, 0x3f, 0xf3, 0xee, 0x2e, 0xdc, 0x62, 0x84, 0x32, 0x5a, 0xa6, 0x21, 0xf6,
	0x7d, 0x12, 0x95, 0x7b, 0x98, 0x3a, 0x7d, 0xb9, 0x76, 0xc9, 0x5b, 0xec, 0x85, 0x2e, 0x29, 0x85,
	0x51, 0xc0, 0x02, 0x94, 0x12, 0x40, 0x75, 0x27, 0x24, 0x11, 0x75, 0x28, 0x2b, 0x07, 0x21, 0x73,
	0x02, 0x9f, 0x4a, 0xab, 0xfa, 0xe1, 0x20, 0x08, 0x06, 0x2e, 0x29, 0x8b, 0x5f, 0xbd, 0xd1, 0xab,
	0x32, 0x73, 0x3c, 0x42, 0x19, 0xf6, 0xc2, 0x18, 0xa0, 0x2d, 0x02, 0x6c, 0x42, 0xfb, 0x91, 0x13,
	0xb2, 0x20, 0x8a, 0x11, 0x3b, 0x52, 0x09, 0x5f, 0xc5, 0x22, 0xff, 0xd6, 0x2f, 0x40, 0xca, 0xf4,
	0x42, 0x36, 0xd6, 0x7f, 0x53, 0x20, 0xd3, 0x0e, 0x3c, 0xc2, 0x86, 0x8e, 0x3f, 0x40, 0x1f, 0x43,
	0x4a, 0x6c, 0xf2, 0x6b, 0x9a, 0x62, 0x6c, 0x55, 0x3f, 0x28, 0x89, 0xd3, 0xa5, 0x29, 0x60, 0xb6,
	0x33, 0x5d, 0x4a, 0x2c, 0x09, 0x46, 0x37, 0x61, 0xd3, 0x1b, 0x13, 0x7f, 0xe4, 0xe5, 0xd7, 0x35,
	0xc5, 0xb8, 0x58, 0xdd, 0x8e, 0x8f, 0x1d, 0x8c, 0x4d, 0x7f, 0xe4, 0x59, 0xb1, 0x11, 0xdd, 0x05,
	0xf0, 0x70, 0x18, 0x12, 0x5b, 0x40, 0x37, 0x04, 0xf4, 0xd2, 0x04, 0x2a, 0x0c, 0x02, 0x9e, 0x00,
	0xa9, 0x37, 0x61, 0x7b, 0xce, 0x23, 0x7a, 0x6f, 0x22, 0x50, 0xd1, 0x14, 0x23, 0x13, 0x0b, 0xd0,
	0x7f, 0x5f, 0x83, 0xec, 0x23, 0x4c, 0x3b, 0x93, 0xec, 0xa0, 0x12, 0x6c, 0xf0, 0x54, 0x09, 0xd4,
	0x56, 0x55, 0x2d, 0xc9, 0x34, 0x95, 0x26, 0x69, 0x2a, 0x4d, 0x91, 0x96, 0xc0, 0xa1, 0x1b, 0xb0,
	0x41, 0x03, 0x8f, 0xc4, 0x61, 0xe7, 0x16, 0xc3, 0xb6, 0x84, 0x15, 0xe5, 0x60, 0x9d, 0xb2, 0x48,
	0x04, 0x99, 0xb1, 0xf8, 0x16, 0x95, 0x20, 0xc5, 0x70, 0xcf, 0x25, 0x22, 0x9a, 0xad, 0x6a, 0x3e,
	0x3e, 0x28, 0x12, 0x6d, 0xca, 0x42, 0x77, 0xb8, 0xdd, 0x92, 0x30, 0x84, 0x60, 0x83, 0xb2, 0x88,
	0xe6, 0x53, 0xda, 0xba, 0x91, 0xb1, 0xc4, 0x1e, 0x55, 0x60, 0x53, 0x18, 0x69, 0x7e, 0x53, 0x5b,
	0x3f, 0x93, 0x24, 0xc6, 0xa1, 0x8f, 0x20, 0xc5, 0xf5, 0xd0, 0xfc, 0x05, 0x71, 0xe0, 0x9f, 0x72,
	0xa5, 0x19, 0x55, 0x20, 0x25, 0x1a, 0x26, 0x9f, 0x16, 0xb8, 0xb3, 0xd2, 0x20, 0x81, 0xc5, 0x1b,
	0xb0, 0x29, 0x8b, 0x86, 0xb2, 0x90, 0x6e, 0x1d, 0x76, 0x1a, 0xad, 0x66, 0xb7, 0x92, 0xfb, 0x5f,
	0xe2, 0xd7, 0xdd, 0x9c, 0x52, 0xd4, 0x01, 0x66, 0xf5, 0x42, 0x19, 0x48, 0xb5, 0x0e, 0x3b, 0x02,
	0x16, 0x6f, 0xef, 0xe6, 0x94, 0xea, 0x1f, 0x0a, 0xa4, 0xcd, 0xb7, 0x2c, 0xc2, 0xed, 0xe8, 0x0d,
	0x6a, 0x00, 0x88, 0xfd, 0x91, 0x8f, 0xa3, 0x31, 0xba, 0x9c, 0x0c, 0xb0, 0x39, 0xf2, 0xac, 0xe0,
	0x2b, 0xaa, 0x2e, 0x8d, 0x5a, 0xcf, 0xfe, 0x72, 0x72, 0xbc, 0x76, 0x01, 0x52, 0x84, 0x33, 0xa0,
	0x3d, 0xd8, 0x12, 0x54, 0x07, 0x84, 0x0d, 0x03, 0x1b, 0x2d, 0x3d, 0xb6, 0x9c, 0x50, 0x7d, 0xfa,
	0xdd, 0xc9, 0xf1, 0xda, 0xa7, 0x60, 0xc2, 0xd5, 0xb6, 0xf9, 0xc4, 0xdc, 0xef, 0x68, 0x45, 0xed,
	0xa1, 0xd5, 0x3a, 0xd0, 0x84, 0x83, 0xee, 0x88, 0x6b, 0x54, 0xa5, 0x37, 0x3d, 0x1b, 0x93, 0x88,
	0xbb, 0x52, 0x9c, 0x08, 0x4f, 0xb6, 0xda, 0xcf, 0x27, 0xc7, 0x6b, 0x4a, 0xf5, 0xcf, 0x1c, 0x64,
	0x0e, 0xc6, 0x6d, 0x79, 0xdd, 0xd1, 0x53, 0xc8, 0x1e, 0xf9, 0x0e, 0x8e, 0xc6, 0x0d, 0x9f, 0x92,
	0x88, 0x9d, 0x47, 0xa4, 0xbe, 0xcd, 0xa3, 0x4e, 0xc3, 0xa6, 0x23, 0x29, 0xa6, 0x94, 0x6d, 0xe2,
	0x92, 0xfe, 0x7f, 0xa3, 0xa4, 0x92, 0x82, 0x80, 0x9a, 0xa4, 0x7c, 0xee, 0xb0, 0x61, 0xdd, 0x89,
	0x48, 0x9f, 0x39, 0x6f, 0x08, 0x3d, 0x97, 0x83, 0xcb, 0xdc, 0xc1, 0x45, 0xc8, 0x4a, 0x07, 0x5d,
	0xc7, 0xb7, 0xc9, 0xdb, 0x99, 0xf2, 0xa3, 0xd0, 0xc6, 0x8c, 0xac, 0x4a, 0x7c, 0x88, 0x23, 0xe6,
	0x60, 0x77, 0x5e, 0xf9, 0x48, 0x52, 0xbc, 0x84, 0x4b, 0x92, 0xb2, 0x4e, 0x5c, 0xc2, 0x88, 0x85,
	0xfd, 0x01, 0x41, 0xd7, 0x97, 0x5e, 0x1b, 0x6e, 0x5e, 0x21, 0x2d, 0xb6, 0x20, 0x43, 0x2d, 0xc8,
	0xb6, 0x49, 0xf4, 0x86, 0x44, 0x6d, 0x16, 0x11, 0xec, 0xa1, 0xdc, 0x5c, 0xb7, 0x62, 0xef, 0x2c,
	0xaa, 0x4b, 0x9c, 0x2a, 0x0b, 0x10, 0x27, 0x00, 0xbb, 0x6e, 0x45, 0x41, 0xcf, 0x00, 0xed, 0xbb,
	0x0e, 0xf1, 0x99, 0x24, 0xfc, 0xd7, 0x9e, 0x38, 0xed, 0x7a, 0xe8, 0xff, 0xe7, 0xcc, 0x00, 0x69,
	0xd9, 0x0e, 0xdd, 0x7b, 0x86, 0x82, 0x9e, 0xcf, 0xf3, 0xca, 0x5c, 0xbc, 0x2b, 0x6f, 0x8e, 0xf3,
	0x6e, 0x41, 0x46, 0x06, 0xdf, 0x75, 0x6c, 0x43, 0x41, 0x36, 0xec, 0x2c, 0x36, 0xc6, 0xa3, 0x20,
	0x78, 0x7d, 0xbe, 0x9e, 0xb8, 0xc2, 0x1d, 0xa0, 0xf9, 0x9e, 0x38, 0x54, 0x5e, 0x28, 0xe8, 0x0b,
	0xd8, 0x49, 0xe6, 0x79, 0xe6, 0xe5, 0x5d, 0x12, 0xbe, 0xc3, 0xd9, 0x73, 0xc9, 0x84, 0x73, 0xee,
	0x8a, 0x82, 0x86, 0x70, 0x2d, 0x99, 0x1c, 0xd9, 0x7b, 0xab, 0x44, 0x72, 0x6a, 0x96, 0xf2, 0xdc,
	0xcd, 0x65, 0xd8, 0xa6, 0x84, 0x75, 0x7d, 0xec, 0x91, 0x2e, 0xa6, 0xf6, 0x2b, 0xee, 0xc9, 0x50,
	0xd4, 0xbf, 0xd2, 0x7c, 0x9c, 0xfc, 0x9a, 0x86, 0x1f, 0x14, 0xa8, 0xc8, 0xe2, 0x6a, 0x8e, 0xcf,
	0x02, 0x2d, 0x7e, 0xd0, 0x77, 0xc5, 0xd0, 0xd6, 0x0c, 0xc7, 0xbe, 0xad, 0x51, 0x86, 0x23, 0xd6,
	0xe5, 0xa3, 0xf6, 0xb6, 0xc6, 0x79, 0x0a, 0x70, 0xe3, 0x19, 0x76, 0x47, 0x84, 0x6a, 0x46, 0x8d,
	0xdb, 0x6b, 0x49, 0x80, 0xde, 0xc3, 0x3e, 0xf6, 0x31, 0xd5, 0x0b, 0x6a, 0x3c, 0x05, 0xf4, 0x2b,
	0x4b, 0x54, 0x17, 0xe7, 0xe6, 0x14, 0x30, 0xb8, 0x3f, 0x9d, 0x6c, 0xaf, 0xa2, 0xc0, 0x5b, 0x90,
	0xf2, 0x7c, 0x48, 0x22, 0xa2, 0x39, 0xf6, 0x6e, 0xcd, 0xb1, 0xb5, 0xbd, 0x66, 0x5d, 0x48, 0xd9,
	0xad, 0xf1, 0x55, 0x8d, 0x87, 0xc3, 0x72, 0x4f, 0x4b, 0x33, 0x07, 0x3f, 0x29, 0xf0, 0xf8, 0x0c,
	0xb7, 0xb5, 0xaf, 0x1f, 0xb6, 0xac, 0x7d, 0xb3, 0xdb, 0x68, 0xd6, 0xcd, 0x17, 0xbb, 0xa2, 0x0f,
	0xbe, 0x39, 0x53, 0xca, 0x5c, 0xcb, 0x2c, 0x17, 0xb4, 0xcc, 0x00, 0xdf, 0x2b, 0xb0, 0x23, 0xeb,
	0xbe, 0x10, 0x3f, 0x14, 0x29, 0x61, 0x89, 0x5a, 0xec, 0xd6, 0x16, 0xeb, 0xb2, 0xab, 0x07, 0x11,
	0x9f, 0x1a, 0x54, 0x07, 0x74, 0x18, 0x39, 0x1e, 0x8e, 0xc6, 0x8f, 0xc9, 0xd8, 0x90, 0x3a, 0x0b,
	0x6a, 0x3c, 0x87, 0x56, 0x2d, 0xc7, 0x97, 0x50, 0xab, 0x9b, 0x4f, 0xcc, 0x8e, 0x39, 0x79, 0xcc,
	0x24, 0xc5, 0xb4, 0x3b, 0x7b, 0x56, 0xc7, 0x88, 0x15, 0x38, 0x76, 0x41, 0x33, 0x9b, 0x75, 0xa3,
	0x46, 0x7c, 0x5b, 0xfc, 0x78, 0xdc, 0x68, 0xd6, 0x8d, 0xfd, 0x56, 0x41, 0x8d, 0xa7, 0xd3, 0xaa,
	0x2e, 0x5f, 0xc2, 0xb5, 0xc5, 0x67, 0x5b, 0xc2, 0xa9, 0x9a, 0xb8, 0x2f, 0xe7, 0x48, 0xec, 0xb7,
	0x0a, 0x1c, 0x34, 0x9a, 0x6d, 0xd3, 0xea, 0x68, 0x8d, 0x66, 0xa7, 0xb5, 0x52, 0xa3, 0x6b, 0xcf,
	0xf6, 0x9e, 0x1c, 0x99, 0xed, 0xd3, 0xfa, 0xfc, 0x5e, 0x41, 0x9d, 0x8e, 0xb5, 0x55, 0xe3, 0xfb,
	0x0c, 0x6e, 0x2e, 0x4f, 0xa9, 0x74, 0x65, 0x88, 0x52, 0xcd, 0x06, 0xdb, 0xaa, 0xd4, 0x03, 0x28,
	0x8f, 0x4e, 0xeb, 0x1a, 0xde, 0x33, 0xa2, 0x37, 0x6e, 0xf1, 0xcb, 0x7f, 0x4b, 0x0b, 0x5f, 0x4f,
	0xfb, 0x61, 0x7e, 0x2e, 0xac, 0xe8, 0xe8, 0xc7, 0x93, 0xe3, 0xb5, 0xfb, 0x70, 0x1d, 0xae, 0x2e,
	0x7d, 0x29, 0xcb, 0x6d, 0xc1, 0xfb, 0x80, 0x26, 0xaf, 0xd2, 0xb3, 0x37, 0xae, 0xdc, 0x45, 0xf1,
	0xd2, 0xf1, 0xe0, 0xc1, 0xe7, 0xb5, 0x81, 0xc3, 0x86, 0xa3, 0x5e, 0xa9, 0x1f, 0x78, 0x65, 0xd6,
	0xf7, 0xfb, 0x6e, 0x30, 0xb2, 0xe5, 0xb7, 0x40, 0xff, 0xce, 0x80, 0xf8, 0x77, 0x26, 0x5f, 0x15,
	0xa7, 0x7c, 0x8d, 0x7c, 0x22, 0xd6, 0xde, 0xa6, 0x40, 0xdf, 0xfb, 0x3b, 0x00, 0x00, 0xff, 0xff,
	0x5e, 0x1e, 0x1f, 0x3b, 0xb1, 0x0c, 0x00, 0x00,
}
