// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/sql/basic/basic.proto

/*
Package basic is a generated protocol buffer package.

It is generated from these files:
	examples/sql/basic/basic.proto

It has these top-level messages:
*/
package basic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/tcncloud/protoc-gen-persist/persist"
import _ "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"
import examples_test "github.com/tcncloud/protoc-gen-persist/examples/test"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Amazing service

type AmazingClient interface {
	UniarySelect(ctx context.Context, in *examples_test.PartialTable, opts ...grpc.CallOption) (*examples_test.ExampleTable, error)
	UniarySelectWithHooks(ctx context.Context, in *examples_test.PartialTable, opts ...grpc.CallOption) (*examples_test.ExampleTable, error)
	ServerStream(ctx context.Context, in *examples_test.Name, opts ...grpc.CallOption) (Amazing_ServerStreamClient, error)
	ServerStreamWithHooks(ctx context.Context, in *examples_test.Name, opts ...grpc.CallOption) (Amazing_ServerStreamWithHooksClient, error)
	Bidirectional(ctx context.Context, opts ...grpc.CallOption) (Amazing_BidirectionalClient, error)
	// Test multi-line query
	BidirectionalWithHooks(ctx context.Context, opts ...grpc.CallOption) (Amazing_BidirectionalWithHooksClient, error)
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (Amazing_ClientStreamClient, error)
	ClientStreamWithHook(ctx context.Context, opts ...grpc.CallOption) (Amazing_ClientStreamWithHookClient, error)
	UnImplementedPersistMethod(ctx context.Context, in *examples_test.ExampleTable, opts ...grpc.CallOption) (*examples_test.ExampleTable, error)
}

type amazingClient struct {
	cc *grpc.ClientConn
}

func NewAmazingClient(cc *grpc.ClientConn) AmazingClient {
	return &amazingClient{cc}
}

func (c *amazingClient) UniarySelect(ctx context.Context, in *examples_test.PartialTable, opts ...grpc.CallOption) (*examples_test.ExampleTable, error) {
	out := new(examples_test.ExampleTable)
	err := grpc.Invoke(ctx, "/examples.Amazing/UniarySelect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amazingClient) UniarySelectWithHooks(ctx context.Context, in *examples_test.PartialTable, opts ...grpc.CallOption) (*examples_test.ExampleTable, error) {
	out := new(examples_test.ExampleTable)
	err := grpc.Invoke(ctx, "/examples.Amazing/UniarySelectWithHooks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *amazingClient) ServerStream(ctx context.Context, in *examples_test.Name, opts ...grpc.CallOption) (Amazing_ServerStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Amazing_serviceDesc.Streams[0], c.cc, "/examples.Amazing/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &amazingServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Amazing_ServerStreamClient interface {
	Recv() (*examples_test.ExampleTable, error)
	grpc.ClientStream
}

type amazingServerStreamClient struct {
	grpc.ClientStream
}

func (x *amazingServerStreamClient) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *amazingClient) ServerStreamWithHooks(ctx context.Context, in *examples_test.Name, opts ...grpc.CallOption) (Amazing_ServerStreamWithHooksClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Amazing_serviceDesc.Streams[1], c.cc, "/examples.Amazing/ServerStreamWithHooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &amazingServerStreamWithHooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Amazing_ServerStreamWithHooksClient interface {
	Recv() (*examples_test.ExampleTable, error)
	grpc.ClientStream
}

type amazingServerStreamWithHooksClient struct {
	grpc.ClientStream
}

func (x *amazingServerStreamWithHooksClient) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *amazingClient) Bidirectional(ctx context.Context, opts ...grpc.CallOption) (Amazing_BidirectionalClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Amazing_serviceDesc.Streams[2], c.cc, "/examples.Amazing/Bidirectional", opts...)
	if err != nil {
		return nil, err
	}
	x := &amazingBidirectionalClient{stream}
	return x, nil
}

type Amazing_BidirectionalClient interface {
	Send(*examples_test.ExampleTable) error
	Recv() (*examples_test.ExampleTable, error)
	grpc.ClientStream
}

type amazingBidirectionalClient struct {
	grpc.ClientStream
}

func (x *amazingBidirectionalClient) Send(m *examples_test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *amazingBidirectionalClient) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *amazingClient) BidirectionalWithHooks(ctx context.Context, opts ...grpc.CallOption) (Amazing_BidirectionalWithHooksClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Amazing_serviceDesc.Streams[3], c.cc, "/examples.Amazing/BidirectionalWithHooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &amazingBidirectionalWithHooksClient{stream}
	return x, nil
}

type Amazing_BidirectionalWithHooksClient interface {
	Send(*examples_test.ExampleTable) error
	Recv() (*examples_test.ExampleTable, error)
	grpc.ClientStream
}

type amazingBidirectionalWithHooksClient struct {
	grpc.ClientStream
}

func (x *amazingBidirectionalWithHooksClient) Send(m *examples_test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *amazingBidirectionalWithHooksClient) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *amazingClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (Amazing_ClientStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Amazing_serviceDesc.Streams[4], c.cc, "/examples.Amazing/ClientStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &amazingClientStreamClient{stream}
	return x, nil
}

type Amazing_ClientStreamClient interface {
	Send(*examples_test.ExampleTable) error
	CloseAndRecv() (*examples_test.NumRows, error)
	grpc.ClientStream
}

type amazingClientStreamClient struct {
	grpc.ClientStream
}

func (x *amazingClientStreamClient) Send(m *examples_test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *amazingClientStreamClient) CloseAndRecv() (*examples_test.NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(examples_test.NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *amazingClient) ClientStreamWithHook(ctx context.Context, opts ...grpc.CallOption) (Amazing_ClientStreamWithHookClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Amazing_serviceDesc.Streams[5], c.cc, "/examples.Amazing/ClientStreamWithHook", opts...)
	if err != nil {
		return nil, err
	}
	x := &amazingClientStreamWithHookClient{stream}
	return x, nil
}

type Amazing_ClientStreamWithHookClient interface {
	Send(*examples_test.ExampleTable) error
	CloseAndRecv() (*examples_test.Ids, error)
	grpc.ClientStream
}

type amazingClientStreamWithHookClient struct {
	grpc.ClientStream
}

func (x *amazingClientStreamWithHookClient) Send(m *examples_test.ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *amazingClientStreamWithHookClient) CloseAndRecv() (*examples_test.Ids, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(examples_test.Ids)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *amazingClient) UnImplementedPersistMethod(ctx context.Context, in *examples_test.ExampleTable, opts ...grpc.CallOption) (*examples_test.ExampleTable, error) {
	out := new(examples_test.ExampleTable)
	err := grpc.Invoke(ctx, "/examples.Amazing/UnImplementedPersistMethod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Amazing service

type AmazingServer interface {
	UniarySelect(context.Context, *examples_test.PartialTable) (*examples_test.ExampleTable, error)
	UniarySelectWithHooks(context.Context, *examples_test.PartialTable) (*examples_test.ExampleTable, error)
	ServerStream(*examples_test.Name, Amazing_ServerStreamServer) error
	ServerStreamWithHooks(*examples_test.Name, Amazing_ServerStreamWithHooksServer) error
	Bidirectional(Amazing_BidirectionalServer) error
	// Test multi-line query
	BidirectionalWithHooks(Amazing_BidirectionalWithHooksServer) error
	ClientStream(Amazing_ClientStreamServer) error
	ClientStreamWithHook(Amazing_ClientStreamWithHookServer) error
	UnImplementedPersistMethod(context.Context, *examples_test.ExampleTable) (*examples_test.ExampleTable, error)
}

func RegisterAmazingServer(s *grpc.Server, srv AmazingServer) {
	s.RegisterService(&_Amazing_serviceDesc, srv)
}

func _Amazing_UniarySelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(examples_test.PartialTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazingServer).UniarySelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.Amazing/UniarySelect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazingServer).UniarySelect(ctx, req.(*examples_test.PartialTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Amazing_UniarySelectWithHooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(examples_test.PartialTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazingServer).UniarySelectWithHooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.Amazing/UniarySelectWithHooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazingServer).UniarySelectWithHooks(ctx, req.(*examples_test.PartialTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _Amazing_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(examples_test.Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AmazingServer).ServerStream(m, &amazingServerStreamServer{stream})
}

type Amazing_ServerStreamServer interface {
	Send(*examples_test.ExampleTable) error
	grpc.ServerStream
}

type amazingServerStreamServer struct {
	grpc.ServerStream
}

func (x *amazingServerStreamServer) Send(m *examples_test.ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func _Amazing_ServerStreamWithHooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(examples_test.Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AmazingServer).ServerStreamWithHooks(m, &amazingServerStreamWithHooksServer{stream})
}

type Amazing_ServerStreamWithHooksServer interface {
	Send(*examples_test.ExampleTable) error
	grpc.ServerStream
}

type amazingServerStreamWithHooksServer struct {
	grpc.ServerStream
}

func (x *amazingServerStreamWithHooksServer) Send(m *examples_test.ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func _Amazing_Bidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AmazingServer).Bidirectional(&amazingBidirectionalServer{stream})
}

type Amazing_BidirectionalServer interface {
	Send(*examples_test.ExampleTable) error
	Recv() (*examples_test.ExampleTable, error)
	grpc.ServerStream
}

type amazingBidirectionalServer struct {
	grpc.ServerStream
}

func (x *amazingBidirectionalServer) Send(m *examples_test.ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func (x *amazingBidirectionalServer) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Amazing_BidirectionalWithHooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AmazingServer).BidirectionalWithHooks(&amazingBidirectionalWithHooksServer{stream})
}

type Amazing_BidirectionalWithHooksServer interface {
	Send(*examples_test.ExampleTable) error
	Recv() (*examples_test.ExampleTable, error)
	grpc.ServerStream
}

type amazingBidirectionalWithHooksServer struct {
	grpc.ServerStream
}

func (x *amazingBidirectionalWithHooksServer) Send(m *examples_test.ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func (x *amazingBidirectionalWithHooksServer) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Amazing_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AmazingServer).ClientStream(&amazingClientStreamServer{stream})
}

type Amazing_ClientStreamServer interface {
	SendAndClose(*examples_test.NumRows) error
	Recv() (*examples_test.ExampleTable, error)
	grpc.ServerStream
}

type amazingClientStreamServer struct {
	grpc.ServerStream
}

func (x *amazingClientStreamServer) SendAndClose(m *examples_test.NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *amazingClientStreamServer) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Amazing_ClientStreamWithHook_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AmazingServer).ClientStreamWithHook(&amazingClientStreamWithHookServer{stream})
}

type Amazing_ClientStreamWithHookServer interface {
	SendAndClose(*examples_test.Ids) error
	Recv() (*examples_test.ExampleTable, error)
	grpc.ServerStream
}

type amazingClientStreamWithHookServer struct {
	grpc.ServerStream
}

func (x *amazingClientStreamWithHookServer) SendAndClose(m *examples_test.Ids) error {
	return x.ServerStream.SendMsg(m)
}

func (x *amazingClientStreamWithHookServer) Recv() (*examples_test.ExampleTable, error) {
	m := new(examples_test.ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Amazing_UnImplementedPersistMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(examples_test.ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AmazingServer).UnImplementedPersistMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.Amazing/UnImplementedPersistMethod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AmazingServer).UnImplementedPersistMethod(ctx, req.(*examples_test.ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

var _Amazing_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examples.Amazing",
	HandlerType: (*AmazingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UniarySelect",
			Handler:    _Amazing_UniarySelect_Handler,
		},
		{
			MethodName: "UniarySelectWithHooks",
			Handler:    _Amazing_UniarySelectWithHooks_Handler,
		},
		{
			MethodName: "UnImplementedPersistMethod",
			Handler:    _Amazing_UnImplementedPersistMethod_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _Amazing_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ServerStreamWithHooks",
			Handler:       _Amazing_ServerStreamWithHooks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Bidirectional",
			Handler:       _Amazing_Bidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "BidirectionalWithHooks",
			Handler:       _Amazing_BidirectionalWithHooks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _Amazing_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStreamWithHook",
			Handler:       _Amazing_ClientStreamWithHook_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "examples/sql/basic/basic.proto",
}

func init() { proto.RegisterFile("examples/sql/basic/basic.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0xd9, 0x8d, 0x41, 0x33, 0x62, 0xa2, 0x23, 0x45, 0x53, 0x13, 0x1d, 0x9b, 0x1e, 0x0a,
	0x29, 0x2d, 0x85, 0x48, 0x62, 0x0c, 0x9a, 0x02, 0xab, 0x34, 0xc2, 0xb6, 0xd9, 0x6e, 0xc5, 0x10,
	0x23, 0x6e, 0x77, 0xa7, 0xed, 0xc8, 0xfe, 0xa9, 0xb3, 0x53, 0x15, 0x8e, 0x18, 0x2f, 0xc6, 0x83,
	0xf5, 0xc8, 0x07, 0x30, 0x7e, 0x84, 0xc6, 0x0f, 0xe0, 0xd5, 0xc4, 0x93, 0xdf, 0x41, 0x4f, 0xde,
	0x4d, 0xcc, 0xec, 0xb6, 0x65, 0x59, 0xa0, 0xd8, 0x2c, 0x5e, 0x26, 0x9d, 0x9d, 0x77, 0xa6, 0xcf,
	0xf3, 0x7b, 0xdf, 0x77, 0x32, 0xe0, 0x3a, 0x7e, 0xad, 0x59, 0x4d, 0x13, 0xbb, 0x59, 0xf7, 0x85,
	0x99, 0xad, 0x6a, 0x2e, 0xd1, 0xfd, 0x31, 0xd3, 0xa4, 0x0e, 0x73, 0xe0, 0xb9, 0xde, 0x7a, 0x3c,
	0xd6, 0xc4, 0xd4, 0x25, 0x2e, 0xcb, 0x3a, 0x4d, 0x46, 0x1c, 0xdb, 0xf5, 0x03, 0xe2, 0x37, 0xea,
	0x8e, 0x53, 0x37, 0x71, 0xd6, 0x9b, 0x55, 0x5b, 0xb5, 0x2c, 0x23, 0x16, 0x76, 0x99, 0x66, 0x35,
	0xbb, 0x01, 0x28, 0x1c, 0x60, 0x60, 0x57, 0xa7, 0xa4, 0xc9, 0x1c, 0xda, 0x8d, 0xb8, 0xda, 0xd7,
	0xc0, 0xb0, 0xcb, 0xbc, 0xc1, 0x5f, 0x99, 0xdd, 0xbd, 0x04, 0xce, 0xe6, 0x2d, 0x6d, 0x87, 0xd8,
	0x75, 0xb8, 0x27, 0x80, 0xb1, 0x8a, 0x4d, 0x34, 0xba, 0x5d, 0xc6, 0x26, 0xd6, 0x19, 0xbc, 0x96,
	0xe9, 0xed, 0xcb, 0x78, 0x5b, 0x4a, 0x1a, 0x65, 0x44, 0x33, 0x55, 0xad, 0x6a, 0xe2, 0x78, 0x78,
	0x51, 0xf2, 0x67, 0xde, 0x62, 0xa2, 0xb4, 0xdb, 0x69, 0x8b, 0x0f, 0xc1, 0xed, 0xb2, 0xb4, 0x2a,
	0x2d, 0xa9, 0x68, 0x0a, 0xd5, 0xa8, 0x63, 0xa1, 0xee, 0x86, 0x4d, 0xc6, 0x63, 0xd0, 0x7a, 0x03,
	0x53, 0x8c, 0x88, 0xb1, 0x90, 0xcc, 0xa1, 0xbc, 0xbc, 0x8c, 0x5c, 0xa6, 0x51, 0xb6, 0xc9, 0xcd,
	0xdd, 0x4d, 0xce, 0x42, 0x91, 0x18, 0x10, 0xec, 0x7f, 0x82, 0x5f, 0x45, 0x10, 0x0b, 0x8a, 0x5b,
	0x27, 0xac, 0xb1, 0xe2, 0x38, 0x5b, 0x6e, 0x04, 0x95, 0xbf, 0x05, 0x2e, 0xf3, 0x97, 0x70, 0x8a,
	0x3a, 0x95, 0x22, 0x98, 0x08, 0xca, 0x5c, 0xc4, 0x35, 0x87, 0x62, 0x2e, 0x14, 0xde, 0xaa, 0x13,
	0xd6, 0x68, 0x55, 0x33, 0xba, 0x63, 0x65, 0x99, 0x6e, 0xeb, 0xa6, 0xd3, 0x32, 0xfc, 0x9c, 0xe9,
	0xd3, 0x75, 0x6c, 0x4f, 0xf7, 0xb2, 0xdf, 0xcf, 0x55, 0x83, 0xdb, 0xdb, 0x90, 0x0f, 0xfa, 0xce,
	0xd7, 0x18, 0xa6, 0x11, 0xce, 0x83, 0x3b, 0x60, 0xac, 0x8c, 0xe9, 0x4b, 0x4c, 0xcb, 0x8c, 0x62,
	0xcd, 0x82, 0x97, 0x43, 0x84, 0x64, 0xcd, 0x3a, 0x01, 0xdb, 0x3c, 0xa7, 0x96, 0x03, 0x93, 0x7d,
	0x68, 0xf7, 0x95, 0xe2, 0x5a, 0x18, 0xda, 0x8a, 0xa4, 0x48, 0xc8, 0xd6, 0x2c, 0xbc, 0x90, 0xcc,
	0xc1, 0x33, 0xfc, 0xc7, 0x8c, 0x00, 0x3f, 0x89, 0x20, 0x16, 0xfc, 0xf3, 0xfd, 0x24, 0x0e, 0xaf,
	0xe2, 0x87, 0x97, 0xbc, 0xef, 0xc2, 0xd0, 0x3a, 0x78, 0x8a, 0x82, 0x22, 0x4e, 0x25, 0x45, 0xc1,
	0x03, 0xa3, 0xa6, 0x68, 0x46, 0x80, 0x5f, 0x04, 0x70, 0x61, 0x91, 0x18, 0x84, 0x62, 0x9d, 0x5f,
	0x05, 0x9a, 0x09, 0x07, 0xb1, 0x18, 0x0c, 0x6a, 0x8b, 0x73, 0xaa, 0x01, 0xb9, 0x52, 0x5a, 0xce,
	0xab, 0x52, 0x88, 0x4f, 0x59, 0x52, 0x51, 0x6a, 0xbf, 0x7c, 0xd3, 0x1e, 0xaa, 0x49, 0xb4, 0x80,
	0x52, 0xc9, 0xd9, 0x34, 0x4a, 0xce, 0x4d, 0x76, 0x09, 0xfa, 0xe5, 0xaf, 0x48, 0x6a, 0x45, 0x91,
	0x0b, 0xf2, 0x03, 0x34, 0x75, 0xa8, 0x41, 0x3d, 0xb6, 0x29, 0x61, 0x46, 0x80, 0x3f, 0x45, 0x30,
	0x71, 0x40, 0xfc, 0xf1, 0xbd, 0xfa, 0xef, 0x2e, 0x3e, 0x8a, 0xdc, 0xc6, 0x7b, 0x11, 0x8c, 0x1f,
	0xe5, 0x03, 0xdc, 0x3c, 0xd1, 0x08, 0x88, 0x1d, 0xe9, 0x04, 0x08, 0xc7, 0x58, 0x51, 0x4a, 0xe0,
	0xca, 0x01, 0x17, 0xd1, 0xeb, 0xa4, 0x18, 0xe2, 0x12, 0xb5, 0x50, 0x3c, 0xda, 0x9f, 0x05, 0x30,
	0xb6, 0x64, 0x12, 0x6c, 0xb3, 0x6e, 0x43, 0x0f, 0x64, 0x3c, 0x11, 0xee, 0xb3, 0x96, 0xa5, 0x38,
	0xaf, 0xdc, 0x84, 0xc6, 0xe9, 0x3e, 0x01, 0xcb, 0x05, 0xb9, 0x2c, 0x29, 0x2a, 0x2a, 0xc8, 0x6a,
	0x31, 0x54, 0x29, 0x29, 0x62, 0xa4, 0xd1, 0x61, 0xc0, 0x8f, 0xf2, 0xab, 0x15, 0xa9, 0x8c, 0x52,
	0xc9, 0x5c, 0x1a, 0x75, 0x49, 0x1f, 0x57, 0x1a, 0xf0, 0x9b, 0x08, 0xc6, 0x83, 0x52, 0x7b, 0x75,
	0x31, 0x58, 0x32, 0x0c, 0x2d, 0x16, 0x0c, 0x37, 0xf1, 0xc6, 0xab, 0x86, 0x3f, 0xc2, 0xff, 0x14,
	0xcc, 0xef, 0x89, 0xa0, 0xda, 0x53, 0xb9, 0x27, 0x82, 0x07, 0x46, 0x4f, 0x3f, 0x7c, 0x0c, 0xe2,
	0x15, 0xbb, 0xc0, 0xbf, 0x59, 0xd8, 0x66, 0xd8, 0x28, 0xf9, 0x81, 0x6b, 0x98, 0x35, 0x1c, 0x23,
	0x42, 0xb7, 0x8d, 0xc4, 0x9f, 0xbf, 0xeb, 0xb4, 0xc5, 0x67, 0xe0, 0x29, 0x88, 0x67, 0xfc, 0xe7,
	0x45, 0xa6, 0xf7, 0xbc, 0xc8, 0xa8, 0xbd, 0xf7, 0xc7, 0xc5, 0xf3, 0x89, 0xd1, 0xb5, 0x6d, 0x3e,
	0x9d, 0x9a, 0x1f, 0xd6, 0x81, 0xb5, 0xcd, 0x49, 0x7f, 0xe8, 0xb4, 0xc5, 0x91, 0xc5, 0xb7, 0xc2,
	0x5e, 0xa7, 0x2d, 0xde, 0x1b, 0xf6, 0x88, 0xfe, 0x7b, 0xea, 0x8e, 0x37, 0x6e, 0x44, 0x3d, 0xa0,
	0x3a, 0xea, 0x05, 0xcf, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x89, 0x05, 0xf0, 0x39, 0xb3, 0x09,
	0x00, 0x00,
}
