// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persist/options.proto

/*
Package persist is a generated protocol buffer package.

It is generated from these files:
	persist/options.proto

It has these top-level messages:
	QueryOpts
	QLImpl
	MOpts
	TypeMapping
*/
package persist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersistenceOptions int32

const (
	PersistenceOptions_SQL     PersistenceOptions = 0
	PersistenceOptions_SPANNER PersistenceOptions = 1
)

var PersistenceOptions_name = map[int32]string{
	0: "SQL",
	1: "SPANNER",
}
var PersistenceOptions_value = map[string]int32{
	"SQL":     0,
	"SPANNER": 1,
}

func (x PersistenceOptions) Enum() *PersistenceOptions {
	p := new(PersistenceOptions)
	*p = x
	return p
}
func (x PersistenceOptions) String() string {
	return proto.EnumName(PersistenceOptions_name, int32(x))
}
func (x *PersistenceOptions) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PersistenceOptions_value, data, "PersistenceOptions")
	if err != nil {
		return err
	}
	*x = PersistenceOptions(value)
	return nil
}
func (PersistenceOptions) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type QueryOpts struct {
	Queries          []*QLImpl `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *QueryOpts) Reset()                    { *m = QueryOpts{} }
func (m *QueryOpts) String() string            { return proto.CompactTextString(m) }
func (*QueryOpts) ProtoMessage()               {}
func (*QueryOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QueryOpts) GetQueries() []*QLImpl {
	if m != nil {
		return m.Queries
	}
	return nil
}

type QLImpl struct {
	Query            []string `protobuf:"bytes,1,rep,name=query" json:"query,omitempty"`
	PmStrategy       *string  `protobuf:"bytes,2,opt,name=pm_strategy,json=pmStrategy" json:"pm_strategy,omitempty"`
	Name             *string  `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *QLImpl) Reset()                    { *m = QLImpl{} }
func (m *QLImpl) String() string            { return proto.CompactTextString(m) }
func (*QLImpl) ProtoMessage()               {}
func (*QLImpl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QLImpl) GetQuery() []string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QLImpl) GetPmStrategy() string {
	if m != nil && m.PmStrategy != nil {
		return *m.PmStrategy
	}
	return ""
}

func (m *QLImpl) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type MOpts struct {
	Query            *string `protobuf:"bytes,1,req,name=query" json:"query,omitempty"`
	Before           *bool   `protobuf:"varint,10,opt,name=before" json:"before,omitempty"`
	After            *bool   `protobuf:"varint,11,opt,name=after" json:"after,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MOpts) Reset()                    { *m = MOpts{} }
func (m *MOpts) String() string            { return proto.CompactTextString(m) }
func (*MOpts) ProtoMessage()               {}
func (*MOpts) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MOpts) GetQuery() string {
	if m != nil && m.Query != nil {
		return *m.Query
	}
	return ""
}

func (m *MOpts) GetBefore() bool {
	if m != nil && m.Before != nil {
		return *m.Before
	}
	return false
}

func (m *MOpts) GetAfter() bool {
	if m != nil && m.After != nil {
		return *m.After
	}
	return false
}

type TypeMapping struct {
	Types            []*TypeMapping_TypeDescriptor `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TypeMapping) Reset()                    { *m = TypeMapping{} }
func (m *TypeMapping) String() string            { return proto.CompactTextString(m) }
func (*TypeMapping) ProtoMessage()               {}
func (*TypeMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TypeMapping) GetTypes() []*TypeMapping_TypeDescriptor {
	if m != nil {
		return m.Types
	}
	return nil
}

type TypeMapping_TypeDescriptor struct {
	ProtoTypeName    *string                                     `protobuf:"bytes,1,opt,name=proto_type_name,json=protoTypeName" json:"proto_type_name,omitempty"`
	ProtoType        *google_protobuf.FieldDescriptorProto_Type  `protobuf:"varint,2,opt,name=proto_type,json=protoType,enum=google.protobuf.FieldDescriptorProto_Type" json:"proto_type,omitempty"`
	ProtoLabel       *google_protobuf.FieldDescriptorProto_Label `protobuf:"varint,3,opt,name=proto_label,json=protoLabel,enum=google.protobuf.FieldDescriptorProto_Label" json:"proto_label,omitempty"`
	XXX_unrecognized []byte                                      `json:"-"`
}

func (m *TypeMapping_TypeDescriptor) Reset()                    { *m = TypeMapping_TypeDescriptor{} }
func (m *TypeMapping_TypeDescriptor) String() string            { return proto.CompactTextString(m) }
func (*TypeMapping_TypeDescriptor) ProtoMessage()               {}
func (*TypeMapping_TypeDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

func (m *TypeMapping_TypeDescriptor) GetProtoTypeName() string {
	if m != nil && m.ProtoTypeName != nil {
		return *m.ProtoTypeName
	}
	return ""
}

func (m *TypeMapping_TypeDescriptor) GetProtoType() google_protobuf.FieldDescriptorProto_Type {
	if m != nil && m.ProtoType != nil {
		return *m.ProtoType
	}
	return google_protobuf.FieldDescriptorProto_TYPE_DOUBLE
}

func (m *TypeMapping_TypeDescriptor) GetProtoLabel() google_protobuf.FieldDescriptorProto_Label {
	if m != nil && m.ProtoLabel != nil {
		return *m.ProtoLabel
	}
	return google_protobuf.FieldDescriptorProto_LABEL_OPTIONAL
}

var E_Pkg = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         560003,
	Name:          "persist.pkg",
	Tag:           "bytes,560003,opt,name=pkg",
	Filename:      "persist/options.proto",
}

var E_Opts = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*MOpts)(nil),
	Field:         560004,
	Name:          "persist.opts",
	Tag:           "bytes,560004,opt,name=opts",
	Filename:      "persist/options.proto",
}

var E_Ql = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*QueryOpts)(nil),
	Field:         560000,
	Name:          "persist.ql",
	Tag:           "bytes,560000,opt,name=ql",
	Filename:      "persist/options.proto",
}

var E_Mapping = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*TypeMapping)(nil),
	Field:         560001,
	Name:          "persist.mapping",
	Tag:           "bytes,560001,opt,name=mapping",
	Filename:      "persist/options.proto",
}

var E_ServiceType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*PersistenceOptions)(nil),
	Field:         560002,
	Name:          "persist.service_type",
	Tag:           "varint,560002,opt,name=service_type,json=serviceType,enum=persist.PersistenceOptions",
	Filename:      "persist/options.proto",
}

func init() {
	proto.RegisterType((*QueryOpts)(nil), "persist.QueryOpts")
	proto.RegisterType((*QLImpl)(nil), "persist.QLImpl")
	proto.RegisterType((*MOpts)(nil), "persist.MOpts")
	proto.RegisterType((*TypeMapping)(nil), "persist.TypeMapping")
	proto.RegisterType((*TypeMapping_TypeDescriptor)(nil), "persist.TypeMapping.TypeDescriptor")
	proto.RegisterEnum("persist.PersistenceOptions", PersistenceOptions_name, PersistenceOptions_value)
	proto.RegisterExtension(E_Pkg)
	proto.RegisterExtension(E_Opts)
	proto.RegisterExtension(E_Ql)
	proto.RegisterExtension(E_Mapping)
	proto.RegisterExtension(E_ServiceType)
}

func init() { proto.RegisterFile("persist/options.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xb1, 0xd3, 0x36, 0x64, 0x0c, 0x69, 0xb5, 0x2a, 0xc8, 0x2a, 0x88, 0x46, 0x41, 0x42,
	0x21, 0xa8, 0x0e, 0xca, 0xa1, 0x82, 0x70, 0x02, 0xb5, 0x48, 0x15, 0x49, 0x9a, 0x6c, 0x38, 0x71,
	0x89, 0x1c, 0x67, 0xe2, 0x5a, 0xd8, 0xde, 0x8d, 0xbd, 0x41, 0xca, 0x8d, 0xaf, 0x77, 0xe0, 0xc2,
	0x4b, 0xf1, 0x46, 0xc8, 0xb3, 0xb6, 0x53, 0x94, 0x4a, 0xe5, 0xe4, 0xdd, 0xbf, 0xe7, 0xff, 0xf3,
	0x7c, 0x19, 0x1e, 0x48, 0x4c, 0xd2, 0x20, 0x55, 0x1d, 0x21, 0x55, 0x20, 0xe2, 0xd4, 0x91, 0x89,
	0x50, 0x82, 0x55, 0x73, 0xf9, 0xa8, 0xe1, 0x0b, 0xe1, 0x87, 0xd8, 0x21, 0x79, 0xb6, 0x5a, 0x74,
	0xe6, 0x98, 0x7a, 0x49, 0x20, 0x95, 0x48, 0x74, 0x68, 0xf3, 0x14, 0x6a, 0xe3, 0x15, 0x26, 0xeb,
	0x4b, 0xa9, 0x52, 0xf6, 0x1c, 0xaa, 0xcb, 0x15, 0x26, 0x01, 0xa6, 0xb6, 0xd1, 0xa8, 0xb4, 0xac,
	0xee, 0xbe, 0x93, 0x93, 0x9c, 0x71, 0xff, 0x22, 0x92, 0x21, 0x2f, 0xde, 0x37, 0x27, 0xb0, 0xa7,
	0x25, 0x76, 0x08, 0xbb, 0x99, 0xb8, 0x26, 0x4b, 0x8d, 0xeb, 0x0b, 0x3b, 0x06, 0x4b, 0x46, 0xd3,
	0x54, 0x25, 0xae, 0x42, 0x7f, 0x6d, 0x9b, 0x0d, 0xa3, 0x55, 0xe3, 0x20, 0xa3, 0x49, 0xae, 0x30,
	0x06, 0x3b, 0xb1, 0x1b, 0xa1, 0x5d, 0x69, 0x98, 0xad, 0x1a, 0xa7, 0x73, 0xf3, 0x03, 0xec, 0x0e,
	0x28, 0x91, 0x6b, 0x4c, 0x73, 0xc3, 0x7c, 0x08, 0x7b, 0x33, 0x5c, 0x88, 0x04, 0x6d, 0x68, 0x18,
	0xad, 0xbb, 0x3c, 0xbf, 0x65, 0xd1, 0xee, 0x42, 0x61, 0x62, 0x5b, 0x24, 0xeb, 0x4b, 0xf3, 0xb7,
	0x09, 0xd6, 0xc7, 0xb5, 0xc4, 0x81, 0x2b, 0x65, 0x10, 0xfb, 0xec, 0x35, 0xec, 0xaa, 0xb5, 0x2c,
	0x4b, 0x7b, 0x5a, 0x96, 0x76, 0x2d, 0x88, 0xce, 0x67, 0x65, 0x8f, 0xb8, 0x76, 0x1c, 0xfd, 0x31,
	0xa0, 0xfe, 0xef, 0x1b, 0xf6, 0x0c, 0xf6, 0xa9, 0x81, 0xd3, 0x2c, 0x62, 0x4a, 0x95, 0x18, 0x54,
	0xe3, 0x7d, 0x92, 0xb3, 0xe8, 0xa1, 0x1b, 0x21, 0xbb, 0x00, 0xd8, 0xc4, 0x51, 0x1b, 0xea, 0xdd,
	0xb6, 0xa3, 0xc7, 0xe2, 0x14, 0x63, 0x71, 0xde, 0x07, 0x18, 0xce, 0x37, 0xf4, 0x51, 0xa6, 0x53,
	0x2e, 0xbc, 0x56, 0xe2, 0x58, 0x1f, 0x2c, 0x8d, 0x0a, 0xdd, 0x19, 0x86, 0x76, 0x85, 0x58, 0x2f,
	0xfe, 0x8f, 0xd5, 0xcf, 0x2c, 0x5c, 0xa7, 0x42, 0xe7, 0x76, 0x1b, 0xd8, 0x48, 0x37, 0x00, 0x63,
	0x0f, 0x2f, 0xf5, 0xfe, 0xb0, 0x2a, 0x54, 0x26, 0xe3, 0xfe, 0xc1, 0x1d, 0x66, 0x41, 0x75, 0x32,
	0x7a, 0x3b, 0x1c, 0x9e, 0xf3, 0x03, 0xa3, 0xf7, 0x12, 0x2a, 0xf2, 0xb3, 0xcf, 0x1e, 0xdf, 0xf0,
	0xad, 0xb0, 0xb0, 0xda, 0x3f, 0x7e, 0x35, 0xa9, 0x01, 0x59, 0x68, 0xef, 0x0c, 0x76, 0x44, 0x36,
	0xc8, 0x27, 0x5b, 0x96, 0x01, 0xaa, 0x2b, 0x31, 0x2f, 0x4c, 0x3f, 0xc9, 0x64, 0x75, 0xeb, 0xe5,
	0x34, 0x68, 0x01, 0x38, 0xb9, 0x7b, 0xe7, 0x60, 0x2e, 0x43, 0x76, 0xbc, 0xc5, 0x98, 0x60, 0xf2,
	0x25, 0x28, 0x93, 0xb6, 0xbf, 0xe6, 0x10, 0xb6, 0xd9, 0xd6, 0x62, 0xa5, 0xb9, 0xb9, 0x0c, 0x7b,
	0x63, 0xa8, 0x46, 0xf9, 0x12, 0xdc, 0xca, 0xfa, 0x96, 0xb3, 0x0e, 0x6f, 0x5a, 0x0f, 0x5e, 0x70,
	0x7a, 0x2e, 0xdc, 0x4b, 0xb5, 0x91, 0x06, 0x7b, 0x3b, 0xf7, 0x3b, 0x71, 0xeb, 0xdd, 0x47, 0x25,
	0x77, 0xbb, 0xfb, 0xdc, 0xca, 0x99, 0xd9, 0x27, 0xdf, 0xbd, 0xfa, 0x74, 0xea, 0x07, 0xea, 0x6a,
	0x35, 0x73, 0x3c, 0x11, 0x75, 0x94, 0x17, 0x7b, 0xa1, 0x58, 0xcd, 0xf5, 0xaf, 0xec, 0x9d, 0xf8,
	0x18, 0x9f, 0x14, 0x3f, 0x7f, 0xfe, 0x7c, 0x93, 0x3f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x36,
	0x05, 0x9e, 0x00, 0x16, 0x04, 0x00, 0x00,
}
