// Code generated by protoc-gen-go. DO NOT EDIT.
// source: persist/options.proto

/*
Package persist is a generated protocol buffer package.

It is generated from these files:
	persist/options.proto

It has these top-level messages:
	QLImpl
	TypeMapping
*/
package persist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PersistenceOptions int32

const (
	// SQL Query
	PersistenceOptions_SQL     PersistenceOptions = 0
	PersistenceOptions_SPANNER PersistenceOptions = 1
)

var PersistenceOptions_name = map[int32]string{
	0: "SQL",
	1: "SPANNER",
}
var PersistenceOptions_value = map[string]int32{
	"SQL":     0,
	"SPANNER": 1,
}

func (x PersistenceOptions) Enum() *PersistenceOptions {
	p := new(PersistenceOptions)
	*p = x
	return p
}
func (x PersistenceOptions) String() string {
	return proto.EnumName(PersistenceOptions_name, int32(x))
}
func (x *PersistenceOptions) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PersistenceOptions_value, data, "PersistenceOptions")
	if err != nil {
		return err
	}
	*x = PersistenceOptions(value)
	return nil
}
func (PersistenceOptions) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type QLImpl struct {
	// the query string with numeric placeholders for parameters
	// its an array to allow the query to span across multiple lines but it
	// will be joined and used as a single sql query string at generation time
	Query []string `protobuf:"bytes,1,rep,name=query" json:"query,omitempty"`
	// in order list of argument names that will be used as parameters for the query
	// the list of arguments represents the field names of the input type message
	Arguments []string `protobuf:"bytes,2,rep,name=arguments" json:"arguments,omitempty"`
	// method level type mapping, if this does not exist it will be
	// used the type mapping at the service level, if that one will not exist
	// it will be used the default one, the code can be found
	// generator/service.go function GetSafeType()
	Mapping *TypeMapping `protobuf:"bytes,4,opt,name=mapping" json:"mapping,omitempty"`
	// the before function will be called before running any sql code for
	// every input data element and if the return will be not empty/nil and
	// the error will be nil the data returned by this function will be
	// returned by the function skipping the code execution
	Before *QLImpl_CallbackFunction `protobuf:"bytes,10,opt,name=before" json:"before,omitempty"`
	// the after function will be called after running any sql code for
	// every output data element, the return data of this function will be ignored
	After            *QLImpl_CallbackFunction `protobuf:"bytes,11,opt,name=after" json:"after,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *QLImpl) Reset()                    { *m = QLImpl{} }
func (m *QLImpl) String() string            { return proto.CompactTextString(m) }
func (*QLImpl) ProtoMessage()               {}
func (*QLImpl) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *QLImpl) GetQuery() []string {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *QLImpl) GetArguments() []string {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *QLImpl) GetMapping() *TypeMapping {
	if m != nil {
		return m.Mapping
	}
	return nil
}

func (m *QLImpl) GetBefore() *QLImpl_CallbackFunction {
	if m != nil {
		return m.Before
	}
	return nil
}

func (m *QLImpl) GetAfter() *QLImpl_CallbackFunction {
	if m != nil {
		return m.After
	}
	return nil
}

// Callback definition function
// define the name and the package of a function with the signature
// func CallbackFunction(message pb.Message) (pb.Message, error)
type QLImpl_CallbackFunction struct {
	// function name
	Name *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	// function go package name in the following formats
	// github.com/repo;package
	// github.com/package
	// dir/package
	// package
	Package          *string `protobuf:"bytes,2,req,name=package" json:"package,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *QLImpl_CallbackFunction) Reset()                    { *m = QLImpl_CallbackFunction{} }
func (m *QLImpl_CallbackFunction) String() string            { return proto.CompactTextString(m) }
func (*QLImpl_CallbackFunction) ProtoMessage()               {}
func (*QLImpl_CallbackFunction) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *QLImpl_CallbackFunction) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *QLImpl_CallbackFunction) GetPackage() string {
	if m != nil && m.Package != nil {
		return *m.Package
	}
	return ""
}

type TypeMapping struct {
	Types            []*TypeMapping_TypeDescriptor `protobuf:"bytes,1,rep,name=types" json:"types,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *TypeMapping) Reset()                    { *m = TypeMapping{} }
func (m *TypeMapping) String() string            { return proto.CompactTextString(m) }
func (*TypeMapping) ProtoMessage()               {}
func (*TypeMapping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TypeMapping) GetTypes() []*TypeMapping_TypeDescriptor {
	if m != nil {
		return m.Types
	}
	return nil
}

type TypeMapping_TypeDescriptor struct {
	// if this is not setup the proto_type must be one of the built-in types
	ProtoTypeName *string `protobuf:"bytes,1,opt,name=proto_type_name,json=protoTypeName" json:"proto_type_name,omitempty"`
	// If proto_type_name is set, this need not be set.  If both this and proto_type_name
	// are set, this must be one of TYPE_ENUM, TYPE_MESSAGE
	// TYPE_GROUP is not supported
	ProtoType *google_protobuf.FieldDescriptorProto_Type `protobuf:"varint,2,opt,name=proto_type,json=protoType,enum=google.protobuf.FieldDescriptorProto_Type" json:"proto_type,omitempty"`
	// if proto_label is not setup we consider any option except LABAEL_REPEATED
	ProtoLabel *google_protobuf.FieldDescriptorProto_Label `protobuf:"varint,3,opt,name=proto_label,json=protoLabel,enum=google.protobuf.FieldDescriptorProto_Label" json:"proto_label,omitempty"`
	// go type name that will be used in the method implementation
	GoType *string `protobuf:"bytes,4,req,name=go_type,json=goType" json:"go_type,omitempty"`
	// go package path
	GoPackage        *string `protobuf:"bytes,5,req,name=go_package,json=goPackage" json:"go_package,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *TypeMapping_TypeDescriptor) Reset()                    { *m = TypeMapping_TypeDescriptor{} }
func (m *TypeMapping_TypeDescriptor) String() string            { return proto.CompactTextString(m) }
func (*TypeMapping_TypeDescriptor) ProtoMessage()               {}
func (*TypeMapping_TypeDescriptor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

func (m *TypeMapping_TypeDescriptor) GetProtoTypeName() string {
	if m != nil && m.ProtoTypeName != nil {
		return *m.ProtoTypeName
	}
	return ""
}

func (m *TypeMapping_TypeDescriptor) GetProtoType() google_protobuf.FieldDescriptorProto_Type {
	if m != nil && m.ProtoType != nil {
		return *m.ProtoType
	}
	return google_protobuf.FieldDescriptorProto_TYPE_DOUBLE
}

func (m *TypeMapping_TypeDescriptor) GetProtoLabel() google_protobuf.FieldDescriptorProto_Label {
	if m != nil && m.ProtoLabel != nil {
		return *m.ProtoLabel
	}
	return google_protobuf.FieldDescriptorProto_LABEL_OPTIONAL
}

func (m *TypeMapping_TypeDescriptor) GetGoType() string {
	if m != nil && m.GoType != nil {
		return *m.GoType
	}
	return ""
}

func (m *TypeMapping_TypeDescriptor) GetGoPackage() string {
	if m != nil && m.GoPackage != nil {
		return *m.GoPackage
	}
	return ""
}

var E_Pkg = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FileOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         560003,
	Name:          "persist.pkg",
	Tag:           "bytes,560003,opt,name=pkg",
	Filename:      "persist/options.proto",
}

var E_Ql = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.MethodOptions)(nil),
	ExtensionType: (*QLImpl)(nil),
	Field:         560000,
	Name:          "persist.ql",
	Tag:           "bytes,560000,opt,name=ql",
	Filename:      "persist/options.proto",
}

var E_Mapping = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*TypeMapping)(nil),
	Field:         560001,
	Name:          "persist.mapping",
	Tag:           "bytes,560001,opt,name=mapping",
	Filename:      "persist/options.proto",
}

var E_ServiceType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.ServiceOptions)(nil),
	ExtensionType: (*PersistenceOptions)(nil),
	Field:         560002,
	Name:          "persist.service_type",
	Tag:           "varint,560002,opt,name=service_type,json=serviceType,enum=persist.PersistenceOptions",
	Filename:      "persist/options.proto",
}

func init() {
	proto.RegisterType((*QLImpl)(nil), "persist.QLImpl")
	proto.RegisterType((*QLImpl_CallbackFunction)(nil), "persist.QLImpl.CallbackFunction")
	proto.RegisterType((*TypeMapping)(nil), "persist.TypeMapping")
	proto.RegisterType((*TypeMapping_TypeDescriptor)(nil), "persist.TypeMapping.TypeDescriptor")
	proto.RegisterEnum("persist.PersistenceOptions", PersistenceOptions_name, PersistenceOptions_value)
	proto.RegisterExtension(E_Pkg)
	proto.RegisterExtension(E_Ql)
	proto.RegisterExtension(E_Mapping)
	proto.RegisterExtension(E_ServiceType)
}

func init() { proto.RegisterFile("persist/options.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x18, 0x24, 0xe9, 0x4f, 0x94, 0x2f, 0xd0, 0xad, 0xac, 0x45, 0x58, 0x65, 0x81, 0xa8, 0x48, 0xa8,
	0x2a, 0x52, 0x8a, 0x7a, 0x40, 0xd0, 0x13, 0xcb, 0xcf, 0x4a, 0x2b, 0x75, 0x4b, 0xeb, 0x72, 0xe2,
	0x52, 0xa5, 0xa9, 0x6b, 0xa2, 0xba, 0xb1, 0x9b, 0xa4, 0x48, 0xbd, 0xf1, 0x73, 0xe2, 0x09, 0xb8,
	0xf2, 0x50, 0x3c, 0x10, 0x8a, 0x9d, 0xa4, 0xb0, 0x5d, 0xb1, 0x7b, 0x73, 0xe6, 0x9b, 0x19, 0x8f,
	0xc7, 0x0e, 0xdc, 0x95, 0x34, 0x4e, 0xc2, 0x24, 0xed, 0x09, 0x99, 0x86, 0x22, 0x4a, 0x3c, 0x19,
	0x8b, 0x54, 0x20, 0x2b, 0x87, 0x5b, 0x2e, 0x13, 0x82, 0x71, 0xda, 0x53, 0xf0, 0x7c, 0xbb, 0xec,
	0x2d, 0x68, 0x12, 0xc4, 0xa1, 0x4c, 0x45, 0xac, 0xa9, 0xed, 0x5f, 0x26, 0xd4, 0x27, 0xc3, 0xf3,
	0xb5, 0xe4, 0xe8, 0x18, 0x6a, 0x9b, 0x2d, 0x8d, 0x77, 0xd8, 0x70, 0x2b, 0x1d, 0x9b, 0xe8, 0x0f,
	0x74, 0x02, 0xb6, 0x1f, 0xb3, 0xed, 0x9a, 0x46, 0x69, 0x82, 0x4d, 0x35, 0xd9, 0x03, 0xc8, 0x03,
	0x6b, 0xed, 0x4b, 0x19, 0x46, 0x0c, 0x57, 0x5d, 0xa3, 0xe3, 0xf4, 0x8f, 0xbd, 0x7c, 0x6f, 0xef,
	0xc3, 0x4e, 0xd2, 0x0b, 0x3d, 0x23, 0x05, 0x09, 0xbd, 0x80, 0xfa, 0x9c, 0x2e, 0x45, 0x4c, 0x31,
	0x28, 0xba, 0x5b, 0xd2, 0x75, 0x08, 0xef, 0x8d, 0xcf, 0xf9, 0xdc, 0x0f, 0x56, 0x67, 0xdb, 0x28,
	0xc8, 0x8e, 0x44, 0x72, 0x3e, 0x7a, 0x0e, 0x35, 0x7f, 0x99, 0xd2, 0x18, 0x3b, 0x37, 0x14, 0x6a,
	0x7a, 0xeb, 0x15, 0x34, 0x2f, 0x8f, 0x10, 0x82, 0x6a, 0xe4, 0xaf, 0x29, 0x36, 0x5c, 0xb3, 0x63,
	0x13, 0xb5, 0x46, 0x18, 0x2c, 0xe9, 0x07, 0x2b, 0x9f, 0x51, 0x6c, 0x2a, 0xb8, 0xf8, 0x6c, 0xff,
	0x36, 0xc1, 0xf9, 0xeb, 0x30, 0xe8, 0x25, 0xd4, 0xd2, 0x9d, 0xa4, 0x89, 0xea, 0xc9, 0xe9, 0x3f,
	0xbe, 0xea, 0xc4, 0x6a, 0xfd, 0xb6, 0x2c, 0x9b, 0x68, 0x45, 0xeb, 0x87, 0x09, 0x8d, 0x7f, 0x27,
	0xe8, 0x09, 0x1c, 0xa9, 0x9b, 0x98, 0x65, 0x8c, 0x59, 0x1e, 0xcb, 0xe8, 0xd8, 0xe4, 0x8e, 0x82,
	0x33, 0xf6, 0x28, 0xcb, 0x77, 0x0e, 0xb0, 0xe7, 0x61, 0xd3, 0x35, 0x3a, 0x8d, 0x7e, 0xd7, 0xd3,
	0xf7, 0xeb, 0x15, 0xf7, 0xeb, 0x9d, 0x85, 0x94, 0x2f, 0xf6, 0xee, 0xe3, 0x0c, 0x57, 0x59, 0x88,
	0x5d, 0xda, 0xa1, 0x21, 0x38, 0xda, 0x8a, 0xfb, 0x73, 0xca, 0x71, 0x45, 0x79, 0x3d, 0xbd, 0x99,
	0xd7, 0x30, 0x93, 0x10, 0x1d, 0x45, 0xad, 0xd1, 0x3d, 0xb0, 0x58, 0x9e, 0xaa, 0xaa, 0x8a, 0xab,
	0x33, 0xbd, 0xcd, 0x03, 0x00, 0x26, 0x66, 0x45, 0xa9, 0x35, 0x35, 0xb3, 0x99, 0x18, 0x6b, 0xa0,
	0xdb, 0x05, 0x34, 0xd6, 0xc5, 0xd1, 0x28, 0xa0, 0xef, 0xf5, 0x03, 0x46, 0x16, 0x54, 0xa6, 0x93,
	0x61, 0xf3, 0x16, 0x72, 0xc0, 0x9a, 0x8e, 0x4f, 0x47, 0xa3, 0x77, 0xa4, 0x69, 0x0c, 0x9e, 0x41,
	0x45, 0xae, 0x18, 0x3a, 0xb9, 0x22, 0x23, 0x2f, 0xa4, 0xf8, 0xfb, 0xcf, 0xb6, 0x2a, 0x2e, 0xa3,
	0x0e, 0x4e, 0xc1, 0xdc, 0x70, 0xf4, 0xf0, 0x40, 0x70, 0x41, 0xd3, 0x4f, 0x62, 0x51, 0x48, 0xbe,
	0x28, 0x89, 0xd3, 0x3f, 0xba, 0xf4, 0x9a, 0x88, 0xb9, 0xe1, 0x83, 0x49, 0xf9, 0xb6, 0xd1, 0xa3,
	0x03, 0x9f, 0x29, 0x8d, 0x3f, 0x87, 0x65, 0x6c, 0xfc, 0x35, 0x37, 0xfa, 0xff, 0xf3, 0x1f, 0xf8,
	0x70, 0x3b, 0xd1, 0x42, 0x55, 0xd8, 0xf5, 0xbe, 0xdf, 0x94, 0x6f, 0xa3, 0x7f, 0xbf, 0xf4, 0x3d,
	0xec, 0x8c, 0x38, 0xb9, 0x67, 0xb6, 0xe5, 0x6b, 0xfb, 0x63, 0xf1, 0xf7, 0xff, 0x09, 0x00, 0x00,
	0xff, 0xff, 0x40, 0xa2, 0xbe, 0xe6, 0x1e, 0x04, 0x00, 0x00,
}
