// Code generated by protoc-gen-go.
// source: examples/spanner/basic/basic_example.proto
// DO NOT EDIT!

/*
Package basic is a generated protocol buffer package.

It is generated from these files:
	examples/spanner/basic/basic_example.proto

It has these top-level messages:
	ExampleTable
	PartialTable
	Name
	NumRows
	ExampleTableRange
*/
package basic

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/tcncloud/protoc-gen-persist/persist"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"
import _ "github.com/tcncloud/protoc-gen-persist/examples/test"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ExampleTable struct {
	Id        int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	StartTime *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	Name      string                      `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *ExampleTable) Reset()                    { *m = ExampleTable{} }
func (m *ExampleTable) String() string            { return proto.CompactTextString(m) }
func (*ExampleTable) ProtoMessage()               {}
func (*ExampleTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ExampleTable) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExampleTable) GetStartTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *ExampleTable) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type PartialTable struct {
	Id        int64                       `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	StartTime *google_protobuf1.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
}

func (m *PartialTable) Reset()                    { *m = PartialTable{} }
func (m *PartialTable) String() string            { return proto.CompactTextString(m) }
func (*PartialTable) ProtoMessage()               {}
func (*PartialTable) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PartialTable) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PartialTable) GetStartTime() *google_protobuf1.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

type Name struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Name) Reset()                    { *m = Name{} }
func (m *Name) String() string            { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()               {}
func (*Name) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type NumRows struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *NumRows) Reset()                    { *m = NumRows{} }
func (m *NumRows) String() string            { return proto.CompactTextString(m) }
func (*NumRows) ProtoMessage()               {}
func (*NumRows) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NumRows) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ExampleTableRange struct {
	StartId int64 `protobuf:"varint,1,opt,name=start_id,json=startId" json:"start_id,omitempty"`
	EndId   int64 `protobuf:"varint,2,opt,name=end_id,json=endId" json:"end_id,omitempty"`
}

func (m *ExampleTableRange) Reset()                    { *m = ExampleTableRange{} }
func (m *ExampleTableRange) String() string            { return proto.CompactTextString(m) }
func (*ExampleTableRange) ProtoMessage()               {}
func (*ExampleTableRange) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ExampleTableRange) GetStartId() int64 {
	if m != nil {
		return m.StartId
	}
	return 0
}

func (m *ExampleTableRange) GetEndId() int64 {
	if m != nil {
		return m.EndId
	}
	return 0
}

func init() {
	proto.RegisterType((*ExampleTable)(nil), "examples.ExampleTable")
	proto.RegisterType((*PartialTable)(nil), "examples.PartialTable")
	proto.RegisterType((*Name)(nil), "examples.Name")
	proto.RegisterType((*NumRows)(nil), "examples.NumRows")
	proto.RegisterType((*ExampleTableRange)(nil), "examples.ExampleTableRange")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MySpanner service

type MySpannerClient interface {
	UniaryInsert(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*ExampleTable, error)
	UniarySelect(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*ExampleTable, error)
	UniaryUpdate(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*PartialTable, error)
	UniaryDelete(ctx context.Context, in *ExampleTableRange, opts ...grpc.CallOption) (*ExampleTable, error)
	NoArgs(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*ExampleTable, error)
	ServerStream(ctx context.Context, in *Name, opts ...grpc.CallOption) (MySpanner_ServerStreamClient, error)
	ClientStreamInsert(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamInsertClient, error)
	ClientStreamDelete(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamDeleteClient, error)
	ClientStreamUpdate(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamUpdateClient, error)
}

type mySpannerClient struct {
	cc *grpc.ClientConn
}

func NewMySpannerClient(cc *grpc.ClientConn) MySpannerClient {
	return &mySpannerClient{cc}
}

func (c *mySpannerClient) UniaryInsert(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*ExampleTable, error) {
	out := new(ExampleTable)
	err := grpc.Invoke(ctx, "/examples.MySpanner/UniaryInsert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniarySelect(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*ExampleTable, error) {
	out := new(ExampleTable)
	err := grpc.Invoke(ctx, "/examples.MySpanner/UniarySelect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniaryUpdate(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*PartialTable, error) {
	out := new(PartialTable)
	err := grpc.Invoke(ctx, "/examples.MySpanner/UniaryUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) UniaryDelete(ctx context.Context, in *ExampleTableRange, opts ...grpc.CallOption) (*ExampleTable, error) {
	out := new(ExampleTable)
	err := grpc.Invoke(ctx, "/examples.MySpanner/UniaryDelete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) NoArgs(ctx context.Context, in *ExampleTable, opts ...grpc.CallOption) (*ExampleTable, error) {
	out := new(ExampleTable)
	err := grpc.Invoke(ctx, "/examples.MySpanner/NoArgs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mySpannerClient) ServerStream(ctx context.Context, in *Name, opts ...grpc.CallOption) (MySpanner_ServerStreamClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MySpanner_serviceDesc.Streams[0], c.cc, "/examples.MySpanner/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MySpanner_ServerStreamClient interface {
	Recv() (*ExampleTable, error)
	grpc.ClientStream
}

type mySpannerServerStreamClient struct {
	grpc.ClientStream
}

func (x *mySpannerServerStreamClient) Recv() (*ExampleTable, error) {
	m := new(ExampleTable)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) ClientStreamInsert(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamInsertClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MySpanner_serviceDesc.Streams[1], c.cc, "/examples.MySpanner/ClientStreamInsert", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerClientStreamInsertClient{stream}
	return x, nil
}

type MySpanner_ClientStreamInsertClient interface {
	Send(*ExampleTable) error
	CloseAndRecv() (*NumRows, error)
	grpc.ClientStream
}

type mySpannerClientStreamInsertClient struct {
	grpc.ClientStream
}

func (x *mySpannerClientStreamInsertClient) Send(m *ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mySpannerClientStreamInsertClient) CloseAndRecv() (*NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) ClientStreamDelete(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamDeleteClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MySpanner_serviceDesc.Streams[2], c.cc, "/examples.MySpanner/ClientStreamDelete", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerClientStreamDeleteClient{stream}
	return x, nil
}

type MySpanner_ClientStreamDeleteClient interface {
	Send(*ExampleTable) error
	CloseAndRecv() (*NumRows, error)
	grpc.ClientStream
}

type mySpannerClientStreamDeleteClient struct {
	grpc.ClientStream
}

func (x *mySpannerClientStreamDeleteClient) Send(m *ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mySpannerClientStreamDeleteClient) CloseAndRecv() (*NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *mySpannerClient) ClientStreamUpdate(ctx context.Context, opts ...grpc.CallOption) (MySpanner_ClientStreamUpdateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MySpanner_serviceDesc.Streams[3], c.cc, "/examples.MySpanner/ClientStreamUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &mySpannerClientStreamUpdateClient{stream}
	return x, nil
}

type MySpanner_ClientStreamUpdateClient interface {
	Send(*ExampleTable) error
	CloseAndRecv() (*NumRows, error)
	grpc.ClientStream
}

type mySpannerClientStreamUpdateClient struct {
	grpc.ClientStream
}

func (x *mySpannerClientStreamUpdateClient) Send(m *ExampleTable) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mySpannerClientStreamUpdateClient) CloseAndRecv() (*NumRows, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NumRows)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MySpanner service

type MySpannerServer interface {
	UniaryInsert(context.Context, *ExampleTable) (*ExampleTable, error)
	UniarySelect(context.Context, *ExampleTable) (*ExampleTable, error)
	UniaryUpdate(context.Context, *ExampleTable) (*PartialTable, error)
	UniaryDelete(context.Context, *ExampleTableRange) (*ExampleTable, error)
	NoArgs(context.Context, *ExampleTable) (*ExampleTable, error)
	ServerStream(*Name, MySpanner_ServerStreamServer) error
	ClientStreamInsert(MySpanner_ClientStreamInsertServer) error
	ClientStreamDelete(MySpanner_ClientStreamDeleteServer) error
	ClientStreamUpdate(MySpanner_ClientStreamUpdateServer) error
}

func RegisterMySpannerServer(s *grpc.Server, srv MySpannerServer) {
	s.RegisterService(&_MySpanner_serviceDesc, srv)
}

func _MySpanner_UniaryInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniaryInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.MySpanner/UniaryInsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniaryInsert(ctx, req.(*ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniarySelect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniarySelect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.MySpanner/UniarySelect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniarySelect(ctx, req.(*ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniaryUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniaryUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.MySpanner/UniaryUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniaryUpdate(ctx, req.(*ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_UniaryDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleTableRange)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).UniaryDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.MySpanner/UniaryDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).UniaryDelete(ctx, req.(*ExampleTableRange))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_NoArgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExampleTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MySpannerServer).NoArgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/examples.MySpanner/NoArgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MySpannerServer).NoArgs(ctx, req.(*ExampleTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _MySpanner_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Name)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MySpannerServer).ServerStream(m, &mySpannerServerStreamServer{stream})
}

type MySpanner_ServerStreamServer interface {
	Send(*ExampleTable) error
	grpc.ServerStream
}

type mySpannerServerStreamServer struct {
	grpc.ServerStream
}

func (x *mySpannerServerStreamServer) Send(m *ExampleTable) error {
	return x.ServerStream.SendMsg(m)
}

func _MySpanner_ClientStreamInsert_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MySpannerServer).ClientStreamInsert(&mySpannerClientStreamInsertServer{stream})
}

type MySpanner_ClientStreamInsertServer interface {
	SendAndClose(*NumRows) error
	Recv() (*ExampleTable, error)
	grpc.ServerStream
}

type mySpannerClientStreamInsertServer struct {
	grpc.ServerStream
}

func (x *mySpannerClientStreamInsertServer) SendAndClose(m *NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mySpannerClientStreamInsertServer) Recv() (*ExampleTable, error) {
	m := new(ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MySpanner_ClientStreamDelete_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MySpannerServer).ClientStreamDelete(&mySpannerClientStreamDeleteServer{stream})
}

type MySpanner_ClientStreamDeleteServer interface {
	SendAndClose(*NumRows) error
	Recv() (*ExampleTable, error)
	grpc.ServerStream
}

type mySpannerClientStreamDeleteServer struct {
	grpc.ServerStream
}

func (x *mySpannerClientStreamDeleteServer) SendAndClose(m *NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mySpannerClientStreamDeleteServer) Recv() (*ExampleTable, error) {
	m := new(ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MySpanner_ClientStreamUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MySpannerServer).ClientStreamUpdate(&mySpannerClientStreamUpdateServer{stream})
}

type MySpanner_ClientStreamUpdateServer interface {
	SendAndClose(*NumRows) error
	Recv() (*ExampleTable, error)
	grpc.ServerStream
}

type mySpannerClientStreamUpdateServer struct {
	grpc.ServerStream
}

func (x *mySpannerClientStreamUpdateServer) SendAndClose(m *NumRows) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mySpannerClientStreamUpdateServer) Recv() (*ExampleTable, error) {
	m := new(ExampleTable)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MySpanner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "examples.MySpanner",
	HandlerType: (*MySpannerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UniaryInsert",
			Handler:    _MySpanner_UniaryInsert_Handler,
		},
		{
			MethodName: "UniarySelect",
			Handler:    _MySpanner_UniarySelect_Handler,
		},
		{
			MethodName: "UniaryUpdate",
			Handler:    _MySpanner_UniaryUpdate_Handler,
		},
		{
			MethodName: "UniaryDelete",
			Handler:    _MySpanner_UniaryDelete_Handler,
		},
		{
			MethodName: "NoArgs",
			Handler:    _MySpanner_NoArgs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _MySpanner_ServerStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ClientStreamInsert",
			Handler:       _MySpanner_ClientStreamInsert_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStreamDelete",
			Handler:       _MySpanner_ClientStreamDelete_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStreamUpdate",
			Handler:       _MySpanner_ClientStreamUpdate_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "examples/spanner/basic/basic_example.proto",
}

func init() { proto.RegisterFile("examples/spanner/basic/basic_example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 797 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x61, 0x8f, 0xdb, 0x34,
	0x18, 0xc7, 0x95, 0x6e, 0x74, 0x3b, 0xaf, 0x9a, 0x98, 0xc5, 0x50, 0xe9, 0x84, 0x66, 0x05, 0xa1,
	0xa5, 0x55, 0xd7, 0xb2, 0x21, 0x4d, 0x20, 0xa8, 0x42, 0xaf, 0x0d, 0x52, 0x47, 0x2f, 0x9d, 0x92,
	0x74, 0xd3, 0xd0, 0xb4, 0xc3, 0x4d, 0xbc, 0xce, 0x28, 0x71, 0x22, 0xdb, 0x65, 0xf4, 0xed, 0xc4,
	0x2b, 0x5e, 0x71, 0x12, 0x12, 0xbc, 0xe5, 0x5b, 0xdc, 0x77, 0xe1, 0xcb, 0x20, 0xc7, 0x6d, 0x2e,
	0x2d, 0x57, 0xee, 0x8a, 0xf6, 0xc6, 0x77, 0x4f, 0xfd, 0xd8, 0xff, 0x5f, 0x9f, 0xe7, 0xf9, 0xd7,
	0xa0, 0x45, 0x7e, 0xc6, 0x49, 0x16, 0x13, 0xd1, 0x15, 0x19, 0x66, 0x8c, 0xf0, 0xee, 0x0c, 0x0b,
	0x1a, 0xea, 0xf5, 0x78, 0xb5, 0xd9, 0xc9, 0x78, 0x2a, 0x53, 0x78, 0x7d, 0x9d, 0xdb, 0xb8, 0x9d,
	0x11, 0x2e, 0xa8, 0x90, 0xdd, 0x34, 0x93, 0x34, 0x65, 0x42, 0x27, 0x34, 0xee, 0xce, 0xd3, 0x74,
	0x1e, 0x93, 0x6e, 0x1e, 0xcd, 0x16, 0xaf, 0xba, 0x92, 0x26, 0x44, 0x48, 0x9c, 0x64, 0xab, 0x04,
	0xb4, 0x9d, 0x10, 0x11, 0x11, 0x72, 0x9a, 0xc9, 0x94, 0xaf, 0x32, 0xea, 0x05, 0x8f, 0x24, 0x42,
	0xe6, 0x8b, 0xde, 0x31, 0x13, 0x50, 0x73, 0xf4, 0x5e, 0x80, 0x67, 0x31, 0x81, 0x37, 0x41, 0x85,
	0x46, 0x75, 0x03, 0x19, 0xd6, 0x15, 0xaf, 0x42, 0x23, 0xf8, 0x25, 0x00, 0x42, 0x62, 0x2e, 0x8f,
	0x95, 0x68, 0xbd, 0x82, 0x0c, 0xeb, 0xc6, 0xc3, 0x46, 0x47, 0x0b, 0x76, 0xd6, 0x82, 0x9d, 0x60,
	0x4d, 0xe4, 0x1d, 0xe4, 0xd9, 0x2a, 0x86, 0x10, 0x5c, 0x65, 0x38, 0x21, 0xf5, 0x2b, 0xc8, 0xb0,
	0x0e, 0xbc, 0xfc, 0x7f, 0xf3, 0x39, 0xa8, 0x3d, 0xc1, 0x5c, 0x52, 0x1c, 0xbf, 0x6b, 0x39, 0xb3,
	0x01, 0xae, 0xba, 0xb8, 0x24, 0x6b, 0x94, 0x64, 0xef, 0x82, 0x6b, 0xee, 0x22, 0xf1, 0xd2, 0x37,
	0x02, 0x7e, 0x00, 0xde, 0x0b, 0xd3, 0x05, 0x93, 0x2b, 0x51, 0x1d, 0x98, 0x0e, 0xb8, 0x55, 0x2e,
	0x83, 0x87, 0xd9, 0x9c, 0xc0, 0x8f, 0xc0, 0x75, 0x0d, 0x53, 0x20, 0x5e, 0xcb, 0xe3, 0x51, 0x04,
	0x6f, 0x83, 0x2a, 0x61, 0x91, 0xda, 0xa8, 0xe8, 0x6b, 0x08, 0x8b, 0x46, 0xd1, 0xc3, 0xbf, 0x01,
	0x38, 0x38, 0x5a, 0xfa, 0xba, 0xe7, 0xf0, 0x2f, 0x03, 0xd4, 0xa6, 0x8c, 0x62, 0xbe, 0x1c, 0x31,
	0x41, 0xb8, 0x84, 0x1f, 0x76, 0xd6, 0x7d, 0xe8, 0x94, 0xd5, 0x1a, 0x3b, 0x3e, 0x37, 0xf1, 0xdb,
	0xd3, 0x93, 0xca, 0x0b, 0xf0, 0x58, 0x1f, 0x47, 0x94, 0xc9, 0x14, 0xad, 0x32, 0x8f, 0xa5, 0xca,
	0x40, 0x16, 0x8d, 0xda, 0xe8, 0xac, 0x62, 0x6d, 0xa4, 0xbe, 0x6e, 0x13, 0xa1, 0xa7, 0x38, 0x5e,
	0x10, 0x81, 0x2c, 0xbb, 0x8d, 0xec, 0x36, 0x32, 0x67, 0x98, 0x61, 0x86, 0x85, 0xd9, 0x84, 0xaa,
	0xc8, 0xa5, 0x12, 0xc3, 0xb7, 0x05, 0xa3, 0x4f, 0x62, 0x12, 0xee, 0xcf, 0x78, 0xa8, 0x18, 0x7b,
	0xe0, 0x81, 0xef, 0x8c, 0x9d, 0x41, 0x80, 0x5a, 0xe8, 0x15, 0x4f, 0x93, 0x2d, 0xca, 0x67, 0xaf,
	0x09, 0x27, 0x88, 0x46, 0x3d, 0x1b, 0xf5, 0xdd, 0x61, 0xce, 0xd8, 0xb3, 0x73, 0x94, 0xbc, 0x3d,
	0xf0, 0x8f, 0x02, 0x62, 0x9a, 0x45, 0x58, 0x92, 0xcb, 0x40, 0x94, 0xc7, 0xc8, 0x7c, 0xa6, 0x20,
	0x3c, 0xf0, 0x8d, 0x3e, 0xbe, 0xa5, 0x2e, 0x88, 0x2c, 0x95, 0xa8, 0x67, 0xeb, 0x22, 0xf5, 0xcc,
	0x94, 0xab, 0x2e, 0x0b, 0x13, 0xbd, 0x29, 0xf0, 0x36, 0x4a, 0xa3, 0xf8, 0x7e, 0x2f, 0xc8, 0x86,
	0x24, 0x26, 0x92, 0xc0, 0x3b, 0xe7, 0x93, 0xe5, 0x03, 0xb3, 0xb3, 0x46, 0x13, 0x85, 0xf7, 0x18,
	0x3c, 0x1a, 0x3a, 0x63, 0x27, 0x70, 0x50, 0xd0, 0x3f, 0x1c, 0x3b, 0xd6, 0xbd, 0x0d, 0xca, 0x7b,
	0x4d, 0xe4, 0x07, 0x7d, 0x2f, 0xb0, 0xec, 0x26, 0x72, 0xdc, 0xa1, 0xfa, 0xf3, 0xdd, 0xc8, 0x1d,
	0x5a, 0x93, 0x49, 0x13, 0x16, 0x53, 0x08, 0x57, 0x43, 0x07, 0x23, 0x50, 0x75, 0xd3, 0x3e, 0x9f,
	0x8b, 0xbd, 0xdb, 0xd5, 0x52, 0x28, 0x9f, 0x82, 0x4f, 0x44, 0xde, 0xed, 0xf3, 0xdb, 0x15, 0xd3,
	0x84, 0x4a, 0xf4, 0x00, 0xbe, 0x00, 0x35, 0x9f, 0xf0, 0x9f, 0x08, 0xf7, 0x25, 0x27, 0x38, 0x81,
	0x37, 0xcf, 0xee, 0x54, 0x4e, 0xdb, 0xa9, 0x61, 0x2a, 0x8d, 0x8f, 0xc1, 0x9d, 0x62, 0x24, 0xbe,
	0xf5, 0x26, 0x47, 0x9b, 0x1a, 0x9f, 0x19, 0xca, 0x1d, 0x70, 0x10, 0x53, 0xc2, 0xa4, 0xbe, 0xfe,
	0x02, 0x8f, 0xdc, 0x2a, 0x89, 0x6b, 0x2b, 0x9b, 0x2f, 0x95, 0xce, 0x73, 0xd0, 0x1f, 0xb9, 0xbe,
	0xe3, 0x05, 0x68, 0xe4, 0x06, 0x93, 0xcb, 0xd9, 0xe3, 0x69, 0x7f, 0x3c, 0x75, 0xfc, 0xb5, 0x3b,
	0xec, 0x7f, 0xbb, 0x22, 0x1f, 0x4b, 0xcb, 0x80, 0xbf, 0x6c, 0x31, 0xae, 0x86, 0x60, 0x0f, 0xc6,
	0xbe, 0x62, 0xfc, 0xfa, 0x7f, 0xb5, 0x7e, 0x30, 0xc8, 0xc1, 0x2c, 0x03, 0xfe, 0xb9, 0x85, 0x71,
	0x81, 0x4b, 0xce, 0xc1, 0x98, 0x2a, 0x8c, 0x27, 0xe0, 0x8b, 0xc5, 0x1e, 0x06, 0xb1, 0x77, 0x19,
	0x43, 0x9b, 0x36, 0x47, 0x6b, 0xfc, 0xf8, 0xeb, 0xe9, 0x49, 0xe5, 0x07, 0xf0, 0x12, 0xfc, 0xc7,
	0xaf, 0xf4, 0xfb, 0x37, 0xcc, 0xea, 0xd1, 0x52, 0x85, 0xad, 0x47, 0x73, 0x2a, 0x5f, 0x2f, 0x66,
	0x9d, 0x30, 0x4d, 0xba, 0x32, 0x64, 0x61, 0x9c, 0x2e, 0x22, 0xfd, 0x6e, 0x85, 0xf7, 0xe7, 0x84,
	0xdd, 0x5f, 0xbf, 0x80, 0xc5, 0x7b, 0x95, 0x2c, 0x95, 0xe4, 0x6f, 0xa7, 0x27, 0x15, 0xe3, 0xd0,
	0xf9, 0x7e, 0xb0, 0xef, 0xf1, 0x8d, 0xe7, 0xf7, 0xab, 0x7c, 0x9d, 0x55, 0xf3, 0x03, 0x9f, 0xff,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x68, 0xc6, 0xe3, 0xd8, 0xa5, 0x07, 0x00, 0x00,
}
